import assert from 'node:assert/strict';
import test from 'node:test';

import {
  toMarkdown,
  toClipboardSummary,
  toShareSheetText,
  toClaudeDebugPacket,
  exportAllFormats,
} from '../presentation-export.ts';
import type { BriefingContent } from '../presentation-export.ts';

const NOW = 1_745_000_000_000;

function brief(overrides: Partial<BriefingContent> = {}): BriefingContent {
  return {
    title: 'Severe Thunderstorm Warning — La Porte, IN',
    generatedAt: NOW,
    summary: 'Damaging wind threat inbound; 35-55 minute arrival window.',
    category: 'weather',
    severityScore: 75,
    confidence: 'high',
    metadata: [
      { label: 'Region', value: 'US-IN (La Porte County)' },
      { label: 'Sources', value: 'NWS, Spotter Reports' },
    ],
    sections: [
      {
        heading: 'Why this matters',
        body: 'Storm cell intersects saved place (Home) within the next hour.',
      },
      {
        heading: 'Action items',
        bullets: [
          'Charge phone + battery packs',
          'Secure outdoor items',
          'Avoid driving until cell passes',
        ],
      },
      {
        heading: 'Watch next',
        bullets: [
          'NWS warning expansion',
          'Power outage reports',
          'Lightning density',
        ],
      },
    ],
    ...overrides,
  };
}

// ── Markdown ────────────────────────────────────────────────────────────

test('markdown: starts with H1 title', () => {
  const md = toMarkdown(brief());
  assert.match(md, /^# Severe Thunderstorm Warning/);
});

test('markdown: includes summary as a blockquote', () => {
  const md = toMarkdown(brief());
  assert.match(md, /^> Damaging wind threat/m);
});

test('markdown: emits category + severity + confidence as bullet line', () => {
  const md = toMarkdown(brief());
  assert.match(md, /\*\*Category:\*\* weather/);
  assert.match(md, /\*\*Severity:\*\* 75\/100/);
  assert.match(md, /\*\*Confidence:\*\* high/);
});

test('markdown: includes metadata items', () => {
  const md = toMarkdown(brief());
  assert.match(md, /\*\*Region:\*\* US-IN/);
  assert.match(md, /\*\*Sources:\*\* NWS, Spotter/);
});

test('markdown: emits H2 per section + bullets', () => {
  const md = toMarkdown(brief());
  assert.match(md, /^## Why this matters$/m);
  assert.match(md, /^## Action items$/m);
  assert.match(md, /^- Charge phone/m);
});

test('markdown: emits a generated-at footer', () => {
  const md = toMarkdown(brief());
  assert.match(md, /As of \d{4}-\d{2}-\d{2}T/);
});

test('markdown: optional Crystal Ball footer', () => {
  const md = toMarkdown(brief(), { includeFooter: true });
  assert.match(md, /Generated by Crystal Ball/);
});

test('markdown: tables render as pipe-formatted rows', () => {
  const md = toMarkdown(brief({
    sections: [{
      heading: 'Confidence breakdown',
      table: {
        columns: ['Driver', 'Score'],
        rows: [['Reliability', '22/25'], ['Freshness', '13/15']],
      },
    }],
  }));
  assert.match(md, /\| Driver \| Score \|/);
  assert.match(md, /\| Reliability \| 22\/25 \|/);
  assert.match(md, /\| --- \| --- \|/);
});

test('markdown: escapes pipes inside cells', () => {
  const md = toMarkdown(brief({
    sections: [{
      heading: 'X',
      table: { columns: ['A'], rows: [['has | pipe']] },
    }],
  }));
  assert.match(md, /has \\\| pipe/);
});

// ── Clipboard summary ──────────────────────────────────────────────────

test('clipboard: includes title + summary + section bullets', () => {
  const c = toClipboardSummary(brief());
  assert.match(c, /Severe Thunderstorm Warning/);
  assert.match(c, /Damaging wind threat/);
  assert.match(c, /Action items:/);
  assert.match(c, /• Charge phone/);
});

test('clipboard: ends with "As of <iso timestamp>"', () => {
  const c = toClipboardSummary(brief());
  // ISO timestamp follows the "As of " prefix.
  assert.match(c, /As of \d{4}-\d{2}-\d{2}T/);
});

test('clipboard: respects maxChars and adds continuation hint', () => {
  // Very tight budget forces truncation.
  const c = toClipboardSummary(brief(), { maxChars: 200 });
  assert.ok(c.length <= 200, `got ${c.length} chars`);
  assert.match(c, /continued in app/);
});

test('clipboard: short brief unchanged', () => {
  const c = toClipboardSummary(brief({ sections: [] }), { maxChars: 1000 });
  assert.ok(!c.includes('continued in app'));
});

// ── Share sheet snippet ────────────────────────────────────────────────

test('share: single line, ≤240 chars by default', () => {
  const s = toShareSheetText(brief());
  assert.ok(!s.includes('\n'));
  assert.ok(s.length <= 240);
});

test('share: includes title + summary', () => {
  const s = toShareSheetText(brief());
  assert.match(s, /Severe Thunderstorm Warning/);
  assert.match(s, /Damaging wind threat/);
});

test('share: long content truncated with ellipsis', () => {
  const long = brief({ summary: 'A'.repeat(500) });
  const s = toShareSheetText(long, { maxChars: 100 });
  assert.ok(s.length <= 100);
  assert.match(s, /…$/);
});

test('share: caller can raise maxChars', () => {
  const s = toShareSheetText(brief(), { maxChars: 500 });
  assert.ok(s.length <= 500);
});

// ── Claude debug packet ────────────────────────────────────────────────

test('debug: parseable JSON', () => {
  const d = toClaudeDebugPacket(brief());
  const parsed = JSON.parse(d) as { schemaVersion: number; title: string };
  assert.equal(parsed.schemaVersion, 1);
  assert.equal(parsed.title, 'Severe Thunderstorm Warning — La Porte, IN');
});

test('debug: includes all fields including metadata + sections', () => {
  const d = toClaudeDebugPacket(brief());
  const parsed = JSON.parse(d) as {
    metadata: { label: string; value: string }[];
    sections: { heading: string }[];
  };
  assert.equal(parsed.metadata.length, 2);
  assert.equal(parsed.sections.length, 3);
  assert.equal(parsed.sections[0]!.heading, 'Why this matters');
});

test('debug: empty optional fields default to undefined or empty array', () => {
  const minimal = brief({ category: undefined, metadata: undefined });
  const parsed = JSON.parse(toClaudeDebugPacket(minimal)) as {
    metadata: unknown[];
    category?: string;
  };
  assert.deepEqual(parsed.metadata, []);
  assert.equal(parsed.category, undefined);
});

// ── exportAllFormats convenience ───────────────────────────────────────

test('exportAllFormats: returns all four output strings', () => {
  const all = exportAllFormats(brief());
  assert.match(all.markdown, /^# /);
  assert.match(all.clipboard, /Severe Thunderstorm/);
  assert.ok(all.share.length > 0);
  assert.match(all.debug, /^\{/);
});

// ── Determinism ────────────────────────────────────────────────────────

test('determinism: same brief → same output bytes', () => {
  const a = toMarkdown(brief());
  const b = toMarkdown(brief());
  assert.equal(a, b);
  const da = toClaudeDebugPacket(brief());
  const db = toClaudeDebugPacket(brief());
  assert.equal(da, db);
});

// ── Plan worked example ────────────────────────────────────────────────

test('integration: plan example "Diesel Stress Rising" story card', () => {
  const dieselBrief: BriefingContent = {
    title: 'Diesel Stress Rising',
    generatedAt: NOW,
    summary: 'Inventories below normal, refinery utilization falling, Gulf storm risk rising.',
    category: 'shortage:diesel',
    severityScore: 65,
    confidence: 'medium',
    sections: [
      {
        heading: 'Why',
        bullets: [
          'Inventories below normal',
          'Refinery utilization falling',
          'Gulf storm risk rising',
        ],
      },
      {
        heading: 'Confidence',
        body: 'Medium, improving',
      },
      {
        heading: 'Watch next',
        bullets: ['EIA update Wednesday', 'Port closures', 'Diesel crack spread'],
      },
      {
        heading: 'Action',
        body: 'Monitor fuel and freight-linked exposure',
      },
    ],
  };
  const md = toMarkdown(dieselBrief);
  assert.match(md, /Diesel Stress Rising/);
  assert.match(md, /## Why/);
  assert.match(md, /Inventories below normal/);
  assert.match(md, /## Confidence/);
  assert.match(md, /## Watch next/);
  assert.match(md, /## Action/);
});
