import type { StoryData } from './story-data';

// Shares carry text and the rendered image only. Story deep links pointed at
// a domain that is not ours (R4-SEC-008), and there is no owned host serving
// /api/story, so no link is generated. Incoming ?c= links are still parsed by
// meta-tags.ts for page metadata.

const NOT_AVAILABLE = 'N/A';
const ATTRIBUTION = 'Generated by Crystal Ball';
const REGIONAL_INDICATOR_A = 0x1_F1_E6;
const LETTER_A = 65;

/** A share line, or `false` to leave it out. */
type ShareLine = string | false;

function joinLines(lines: ShareLine[]): string {
  return lines.filter((line): line is string => line !== false).join('\n');
}

function regionalIndicator(letter: number | undefined): number {
  return REGIONAL_INDICATOR_A + (letter ?? LETTER_A) - LETTER_A;
}

/** Two-letter ISO code to flag emoji; anything else yields no flag. */
export function countryFlag(code: string): string {
  const upper = code.toUpperCase();
  if (!/^[A-Z]{2}$/.test(upper)) return '';
  return String.fromCodePoint(regionalIndicator(upper.codePointAt(0)), regionalIndicator(upper.codePointAt(1)));
}

function signed(value: number): string {
  return value > 0 ? `+${value}` : String(value);
}

function ciiText(data: StoryData): { score: string; level: string; trend: string; change24h: string } {
  const { cii } = data;
  if (!cii) return { score: NOT_AVAILABLE, level: NOT_AVAILABLE, trend: 'stable', change24h: NOT_AVAILABLE };
  return { score: String(cii.score), level: cii.level, trend: cii.trend, change24h: signed(cii.change24h) };
}

// Share text templates for different platforms. Text only: no URLs.
export const shareTexts = {
  twitter: (data: StoryData): string => {
    const cii = ciiText(data);
    return joinLines([
      `${countryFlag(data.countryCode)} ${data.countryName} Intelligence Brief`,
      '',
      `Instability: ${cii.score}/100 (${cii.level})`,
      data.threats.critical > 0 && `⚠️ ${data.threats.critical} critical threats`,
      '',
      ATTRIBUTION,
    ]);
  },

  whatsapp: (data: StoryData): string => {
    const cii = ciiText(data);
    return joinLines([
      `${countryFlag(data.countryCode)} *${data.countryName} Intelligence Brief*`,
      '',
      `*Instability:* ${cii.score}/100 (${cii.level})`,
      `*Trend:* ${cii.trend}`,
      data.threats.critical > 0 && `*⚠️ Critical:* ${data.threats.critical}`,
      data.threats.high > 0 && `*🔴 High:* ${data.threats.high}`,
      '',
      ATTRIBUTION,
    ]);
  },

  linkedin: (data: StoryData): string => {
    const cii = ciiText(data);
    return joinLines([
      `Intelligence Update: ${data.countryName}`,
      '',
      'Real-time instability assessment:',
      `• Score: ${cii.score}/100 (${cii.level})`,
      `• 24h change: ${cii.change24h}%`,
      data.threats.critical > 0 && `• Critical threats: ${data.threats.critical}`,
      '',
      'Data via Crystal Ball - Open source geopolitical intelligence',
    ]);
  },

  telegram: (data: StoryData): string => {
    const cii = ciiText(data);
    const change = data.cii?.change24h;
    return joinLines([
      `${countryFlag(data.countryCode)} *${data.countryName} Intelligence*`,
      '',
      `📊 Instability: *${cii.score}/100* (${cii.level})`,
      `📈 Trend: *${cii.trend}*`,
      Boolean(change) && `📉 24h: *${cii.change24h}*`,
      data.threats.critical > 0 && `🚨 Critical: *${data.threats.critical}*`,
      data.threats.high > 0 && `🔴 High: *${data.threats.high}*`,
      '',
      ATTRIBUTION,
    ]);
  },
};

// Text-only share intents (no story link; see above).
export function getShareUrls(data: StoryData): Record<'twitter' | 'linkedin' | 'whatsapp', string> {
  return {
    twitter: `https://twitter.com/intent/tweet?text=${encodeURIComponent(shareTexts.twitter(data))}`,
    linkedin: `https://www.linkedin.com/feed/?shareActive=true&text=${encodeURIComponent(shareTexts.linkedin(data))}`,
    whatsapp: `https://wa.me/?text=${encodeURIComponent(shareTexts.whatsapp(data))}`,
  };
}
