/**
 * Presentation export — per
 * docs/INSIGHTS_NOTIFICATIONS_PRESENTATION_PLAN.md PR 6 (lines 419-426)
 * and section 14 (lines 321-339).
 *
 * Formats a structured briefing into multiple output forms:
 *   - Markdown brief (full context, ready for the share sheet)
 *   - Clipboard summary (one-paragraph plain text)
 *   - Share-sheet snippet (tweet-sized)
 *   - Claude debug packet (JSON)
 *
 * Pure deterministic: no DOM, no fetch, no clipboard side effects. The
 * UI layer (PR 5) hooks these formatters into actual share sheets and
 * clipboard APIs; this module is the pure formatter contract.
 *
 * Plan invariants:
 *   - Output must be readable by a human and machine-parseable for
 *     the Claude debug packet path.
 *   - No raw newlines in the share-sheet snippet (single line).
 */

// ── Public types ─────────────────────────────────────────────────────────

export interface BriefingMetadataItem {
  label: string;
  value: string;
}

export interface BriefingTable {
  columns: readonly string[];
  rows: readonly (readonly string[])[];
}

export interface BriefingSection {
  heading: string;
  /** Optional paragraph body. */
  body?: string;
  /** Optional bullet list. */
  bullets?: readonly string[];
  /** Optional structured table. */
  table?: BriefingTable;
}

export interface BriefingContent {
  /** Title shown at the top of the brief and as the subject line. */
  title: string;
  /** ms timestamp when the brief was generated. */
  generatedAt: number;
  /** One-sentence summary used in clipboard + share contexts. */
  summary: string;
  /** Optional categorical tag (e.g. "weather", "shortage:wheat"). */
  category?: string;
  /** Optional severity / risk score for headline emphasis. */
  severityScore?: number;
  /** Optional confidence label. */
  confidence?: 'low' | 'medium' | 'high';
  /** Display-friendly key/value pairs (location, region, source count). */
  metadata?: readonly BriefingMetadataItem[];
  /** Body sections, ordered. */
  sections: readonly BriefingSection[];
}

// ── Markdown ─────────────────────────────────────────────────────────────

export interface MarkdownOptions {
  /** When true, includes a "Generated by Crystal Ball" footer. */
  includeFooter?: boolean;
}

export function toMarkdown(content: BriefingContent, options: MarkdownOptions = {}): string {
  const lines = [
    ...renderHeader(content),
    ...renderTags(content),
    ...renderMetadata(content),
    ...renderSections(content.sections),
    ...renderFooter(content, options),
  ];
  return lines.join('\n');
}

function renderHeader(content: BriefingContent): string[] {
  return [
    `# ${escapeMd(content.title)}`,
    '',
    `> ${escapeMd(content.summary)}`,
    '',
  ];
}

function renderTags(content: BriefingContent): string[] {
  const tags: string[] = [];
  if (content.category) tags.push(`**Category:** ${escapeMd(content.category)}`);
  if (content.severityScore !== undefined) tags.push(`**Severity:** ${content.severityScore}/100`);
  if (content.confidence) tags.push(`**Confidence:** ${escapeMd(content.confidence)}`);
  if (tags.length === 0) return [];
  return [tags.join(' • '), ''];
}

function renderMetadata(content: BriefingContent): string[] {
  if (!content.metadata || content.metadata.length === 0) return [];
  return [
    ...content.metadata.map((item) => `- **${escapeMd(item.label)}:** ${escapeMd(item.value)}`),
    '',
  ];
}

function renderSections(sections: readonly BriefingSection[]): string[] {
  return sections.flatMap((s) => renderSection(s));
}

function renderSection(section: BriefingSection): string[] {
  const out: string[] = [`## ${escapeMd(section.heading)}`];
  if (section.body) out.push('', escapeMd(section.body));
  if (section.bullets && section.bullets.length > 0) {
    out.push('', ...section.bullets.map((b) => `- ${escapeMd(b)}`));
  }
  if (section.table) out.push('', ...renderTable(section.table));
  out.push('');
  return out;
}

function renderFooter(content: BriefingContent, options: MarkdownOptions): string[] {
  const out = ['---', `_As of ${new Date(content.generatedAt).toISOString()}_`];
  if (options.includeFooter) out.push('', '_Generated by Crystal Ball._');
  return out;
}

function renderTable(table: BriefingTable): string[] {
  const headerRow = `| ${table.columns.map((c) => escapeMd(c)).join(' | ')} |`;
  const separatorRow = `| ${table.columns.map(() => '---').join(' | ')} |`;
  const dataRows = table.rows.map((row) => {
    const padded: string[] = [...row];
    while (padded.length < table.columns.length) padded.push('');
    return `| ${padded.slice(0, table.columns.length).map((c) => escapeMd(c)).join(' | ')} |`;
  });
  return [headerRow, separatorRow, ...dataRows];
}

function escapeMd(text: string): string {
  // Minimal escape: pipes (table-breaking), backticks (formatting),
  // leading hash (heading hijack). Don't aggressively escape — the
  // brief is not user-input, it's our own formatted content.
  return text.replace(/\|/g, String.raw`\|`).replace(/`/g, '\\`');
}

// ── Clipboard summary ────────────────────────────────────────────────────

export interface ClipboardOptions {
  /** Maximum characters. Default 1000. Long briefs are truncated with
   *  "…" and a "(continued in app)" tail. */
  maxChars?: number;
}

export function toClipboardSummary(
  content: BriefingContent,
  options: ClipboardOptions = {},
): string {
  const max = options.maxChars ?? 1000;
  const head = `${content.title}\n${content.summary}\n\n`;
  const sections: string[] = [];
  for (const s of content.sections) {
    const parts: string[] = [s.heading + ':'];
    if (s.body) parts.push(s.body);
    if (s.bullets && s.bullets.length > 0) {
      for (const b of s.bullets) parts.push(`• ${b}`);
    }
    sections.push(parts.join('\n'));
  }
  const tail = `\n\nAs of ${new Date(content.generatedAt).toISOString()}`;
  const full = head + sections.join('\n\n') + tail;
  if (full.length <= max) return full;
  // Truncate body, preserve title + summary + as-of.
  const overhead = head.length + tail.length + 24; // 24 chars for "… (continued in app)\n"
  const body = sections.join('\n\n');
  const room = Math.max(0, max - overhead);
  const truncated = body.slice(0, room).replace(/\s\S*$/, '');
  return `${head}${truncated}…\n(continued in app)${tail}`;
}

// ── Share-sheet snippet ──────────────────────────────────────────────────

export interface ShareOptions {
  /** Cap on length (Tweet/SMS-friendly). Default 240. */
  maxChars?: number;
}

export function toShareSheetText(
  content: BriefingContent,
  options: ShareOptions = {},
): string {
  const max = options.maxChars ?? 240;
  // Collapse newlines so the snippet stays a single line.
  const single = `${content.title}: ${content.summary}`.replace(/\s+/g, ' ').trim();
  if (single.length <= max) return single;
  return `${single.slice(0, Math.max(0, max - 1)).replace(/\s\S*$/, '')}…`;
}

// ── Claude debug packet ──────────────────────────────────────────────────
//
// Purpose: a structured JSON snapshot of the briefing, ready to paste
// into Claude or attach to a bug report. We intentionally don't shorten
// or pretty-print the content — the consumer is a model / dev, not a
// human reader.

export function toClaudeDebugPacket(content: BriefingContent): string {
  const packet = {
    schemaVersion: 1,
    title: content.title,
    summary: content.summary,
    category: content.category,
    severityScore: content.severityScore,
    confidence: content.confidence,
    generatedAt: content.generatedAt,
    metadata: content.metadata ?? [],
    sections: content.sections.map((s) => ({
      heading: s.heading,
      body: s.body,
      bullets: s.bullets,
      table: s.table,
    })),
  };
  return JSON.stringify(packet, undefined, 2);
}

// ── Convenience builders ─────────────────────────────────────────────────
//
// The plan section 14 lists Markdown / PNG / PDF / Clipboard / Share
// sheet / Send-to-Claude as desired output formats. PR 6 ships the four
// pure-text variants (Markdown, Clipboard, Share, Debug). PNG and PDF
// require DOM rendering and arrive with PR 5 (UI).

export function exportAllFormats(content: BriefingContent): {
  markdown: string;
  clipboard: string;
  share: string;
  debug: string;
} {
  return {
    markdown: toMarkdown(content),
    clipboard: toClipboardSummary(content),
    share: toShareSheetText(content),
    debug: toClaudeDebugPacket(content),
  };
}
