/**
 * claude-agent.js characterization tests
 * Generated by api/__tests__/_scaffold-generator.mjs
 *
 * TODO: Fill in handler-specific assertions. Each test currently validates
 * only the response contract (status code is 2xx/4xx/5xx appropriately,
 * body is present). Customize the upstream mock responses for real coverage.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mockReq, mockRes, mockFetch } from './_test-utils.mjs';

let handler;
try {
  handler = (await import('../claude-agent.js')).default
    ?? (await import('../claude-agent.js'));
} catch (err) {
  console.warn('Handler claude-agent.js failed to import:', err.message);
  handler = null;
}

test('claude-agent.js: rejects unsupported methods', async () => {
  if (!handler) return;
  const req = mockReq({ method: 'DELETE' });
  const res = mockRes();
  await handler(req, res);
  assert.ok(res.statusCode === 405 || res.statusCode === 400 || res.statusCode === 200,
    'should handle or reject unsupported methods');
});

test('claude-agent.js: handles missing query params gracefully', async () => {
  if (!handler) return;
  const req = mockReq({ query: {} });
  const res = mockRes();
  const restoreFetch = mockFetch(new Map([
    ['http', { status: 200, json: {} }],
  ]));
  try { await handler(req, res); } catch {} finally { restoreFetch(); }
  assert.ok(res.ended || res.body !== null, 'should respond');
});
