/**
 * telegram-feed.js characterization tests
 * Generated by api/__tests__/_scaffold-generator.mjs
 *
 * TODO: Fill in handler-specific assertions. Each test currently validates
 * only the response contract (status code is 2xx/4xx/5xx appropriately,
 * body is present). Customize the upstream mock responses for real coverage.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { invokeHandler, mockFetch } from './_test-utils.mjs';

let handler;
try {
  handler = (await import('../telegram-feed.js')).default
    ?? (await import('../telegram-feed.js'));
} catch (err) {
  console.warn('Handler telegram-feed.js failed to import:', err.message);
  handler = null;
}

test('telegram-feed.js: rejects unsupported methods', async () => {
  if (!handler) return;
  const { res } = await invokeHandler(handler, { method: 'DELETE' });
  assert.ok(res.ended, 'should respond to unsupported methods without throwing');
});

test('telegram-feed.js: handles missing query params gracefully', async () => {
  if (!handler) return;
  const restoreFetch = mockFetch(new Map([
    ['http', { status: 200, json: {} }],
  ]));
  let res;
  try { ({ res } = await invokeHandler(handler, { query: {} })); } finally { restoreFetch(); }
  assert.ok(res.ended || res.body !== null, 'should respond');
});
