/**
 * version.js characterization tests
 * Generated by api/__tests__/_scaffold-generator.mjs
 *
 * TODO: Fill in handler-specific assertions. Each test currently validates
 * only the response contract (status code is 2xx/4xx/5xx appropriately,
 * body is present). Customize the upstream mock responses for real coverage.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { invokeHandler, mockFetch } from './_test-utils.mjs';

let handler;
try {
  handler = (await import('../version.js')).default
    ?? (await import('../version.js'));
} catch (err) {
  console.warn('Handler version.js failed to import:', err.message);
  handler = null;
}

test('version.js: rejects unsupported methods', async () => {
  if (!handler) return;
  const { res } = await invokeHandler(handler, { method: 'DELETE' });
  assert.ok(res.ended, 'should respond to unsupported methods without throwing');
});

test('version.js: handles missing query params gracefully', async () => {
  if (!handler) return;
  const restoreFetch = mockFetch(new Map([
    ['http', { status: 200, json: {} }],
  ]));
  let res;
  try { ({ res } = await invokeHandler(handler, { query: {} })); } finally { restoreFetch(); }
  assert.ok(res.ended || res.body !== null, 'should respond');
});

// R2-SEC-010: wildcard CORS is an approved exception on this public read-only endpoint.
// This test documents and pins that it is intentional.
test('version.js: uses wildcard CORS (approved public-endpoint exception)', async () => {
  if (!handler) return;
  const upstream = {
    tag_name: 'v1.2.3',
    html_url: 'https://github.com/bradleybond512/crystal-ball/releases/tag/v1.2.3',
    prerelease: false,
  };
  const restoreFetch = mockFetch(new Map([
    ['github.com', { status: 200, json: upstream }],
  ]));
  let response;
  try {
    ({ response } = await invokeHandler(handler, {}));
  } finally {
    restoreFetch();
  }
  const corsHeader = response?.headers?.get('access-control-allow-origin');
  assert.equal(corsHeader, '*', 'version endpoint must serve wildcard CORS (public read-only exception)');
});
