import { strict as assert } from 'node:assert';
import test from 'node:test';
import type { StoryData } from '../story-data';
import { countryFlag, getShareUrls, shareTexts } from '../story-share';

function story(overrides: Partial<StoryData> = {}): StoryData {
  return {
    countryCode: 'ua',
    countryName: 'Ukraine',
    cii: { score: 72, level: 'high', trend: 'rising', components: {} as never, change24h: 3 },
    news: [],
    theater: null,
    markets: [],
    threats: { critical: 2, high: 0, medium: 0, categories: [] },
    signals: { protests: 0, militaryFlights: 0, militaryVessels: 0, outages: 0, gpsJammingHexes: 0 },
    convergence: null,
    ...overrides,
  };
}

test('share texts keep their layout and carry no link or third-party handle', () => {
  const data = story();
  assert.equal(shareTexts.twitter(data), '🇺🇦 Ukraine Intelligence Brief\n\nInstability: 72/100 (high)\n⚠️ 2 critical threats\n\nGenerated by Crystal Ball');
  assert.equal(shareTexts.whatsapp(data), '🇺🇦 *Ukraine Intelligence Brief*\n\n*Instability:* 72/100 (high)\n*Trend:* rising\n*⚠️ Critical:* 2\n\nGenerated by Crystal Ball');
  assert.equal(shareTexts.linkedin(data), 'Intelligence Update: Ukraine\n\nReal-time instability assessment:\n• Score: 72/100 (high)\n• 24h change: +3%\n• Critical threats: 2\n\nData via Crystal Ball - Open source geopolitical intelligence');
  assert.equal(shareTexts.telegram(data), '🇺🇦 *Ukraine Intelligence*\n\n📊 Instability: *72/100* (high)\n📈 Trend: *rising*\n📉 24h: *+3*\n🚨 Critical: *2*\n\nGenerated by Crystal Ball');
  for (const render of Object.values(shareTexts)) {
    assert.doesNotMatch(render(data), /https?:|www\.|@\w/);
  }
});

test('missing or zero CII values render honestly', () => {
  const none = story({ cii: null, threats: { critical: 0, high: 1, medium: 0, categories: [] } });
  assert.equal(shareTexts.twitter(none), '🇺🇦 Ukraine Intelligence Brief\n\nInstability: N/A/100 (N/A)\n\nGenerated by Crystal Ball');
  assert.match(shareTexts.whatsapp(none), /\*Trend:\* stable\n\*🔴 High:\* 1\n/);
  assert.match(shareTexts.linkedin(none), /• 24h change: N\/A%\n\nData via/);
  assert.doesNotMatch(shareTexts.telegram(none), /24h/);

  const zero = story({ cii: { score: 0, level: 'low', trend: 'falling', components: {} as never, change24h: -2 } });
  assert.match(shareTexts.twitter(zero), /Instability: 0\/100 \(low\)/);
  assert.match(shareTexts.linkedin(zero), /• 24h change: -2%/);
  assert.match(shareTexts.telegram(zero), /📉 24h: \*-2\*/);
});

test('flags only for two-letter codes', () => {
  assert.equal(countryFlag('us'), '🇺🇸');
  for (const code of ['', 'u', 'usa', '1a', 'é1']) assert.equal(countryFlag(code), '', code);
});

test('share intents are text-only on fixed hosts', () => {
  const urls = getShareUrls(story());
  assert.deepEqual(Object.keys(urls).sort(), ['linkedin', 'twitter', 'whatsapp']);
  assert.ok(urls.twitter.startsWith('https://twitter.com/intent/tweet?text='));
  assert.ok(urls.linkedin.startsWith('https://www.linkedin.com/feed/?shareActive=true&text='));
  assert.ok(urls.whatsapp.startsWith('https://wa.me/?text='));
  for (const url of Object.values(urls)) {
    const parsed = new URL(url);
    assert.deepEqual([...parsed.searchParams.keys()].filter((k) => k !== 'shareActive'), ['text']);
    assert.doesNotMatch(parsed.searchParams.get('text') ?? '', /https?:/);
  }
});
