import type { PanelConfig, MapLayers } from '@/types';
import type { DataSourceId } from '@/services/data-freshness';
import { SITE_VARIANT } from './variant';

// ============================================
// FULL VARIANT (Geopolitical)
// ============================================
// Panel order matters. Lead with watchlists and escalation workflow before raw feeds.
const FULL_PANELS: Record<string, PanelConfig> = {
  'threat-dashboard': { name: 'Threat Dashboard', enabled: true, priority: 1 },
  map: { name: 'Global Map', enabled: true, priority: 1 },
  watchlist: { name: 'Watchlist & Playbooks', enabled: true, priority: 1 },
  'saved-places': { name: 'Saved Places', enabled: true, priority: 1 },
  'watchlist-locations': { name: 'Watched Locations', enabled: true, priority: 1 },
  'local-logistics': { name: 'Local Logistics', enabled: true, priority: 1 },
  'comms-plan': { name: 'Tactical Comms', enabled: true, priority: 1 },
  'unified-alert-inbox': { name: 'Alert Inbox', enabled: true, priority: 1 },
  'alert-rules': { name: 'Alert Rules', enabled: true, priority: 1 },
  'situation-awareness': { name: 'Situation Awareness', enabled: true, priority: 1 },
  'alert-center': { name: 'Alert Center', enabled: true, priority: 1 },
  'intelligence-feed': { name: 'Intelligence Feed', enabled: true, priority: 1 },
  'intelligence-timeline': { name: 'Intelligence Timeline', enabled: true, priority: 1 },
  'strategic-risk': { name: 'Strategic Risk Overview', enabled: true, priority: 1 },
  'strategic-posture': { name: 'AI Strategic Posture', enabled: true, priority: 1 },
  insights: { name: 'AI Insights', enabled: true, priority: 1 },
  // Out of the default layout: overlaps 'maritime-superpower' (Maritime
  // Intelligence), which now hosts the freight-stress section. The component
  // stays registered so saved user layouts and the Settings toggle keep working.
  'maritime-intel': { name: 'Maritime Intel', enabled: false, priority: 1 },
  'maritime-superpower': { name: 'Maritime Intelligence', enabled: true, priority: 1 },
  'health-superpower': { name: 'Health Intelligence', enabled: true, priority: 1 },
  'personal-resilience': { name: 'Personal Resilience', enabled: true, priority: 1 },
  'supply-chain-disruption': { name: 'Supply Chain Disruption', enabled: true, priority: 1 },
  cii: { name: 'Country Instability', enabled: true, priority: 1 },
  'geo-hubs': { name: 'Geopolitical Hubs', enabled: true, priority: 1 },
  'live-news': { name: 'Live News', enabled: true, priority: 1 },
  'live-webcams': { name: 'Live Webcams', enabled: true, priority: 1 },
  intel: { name: 'Intel Feed', enabled: true, priority: 1 },
  'gdelt-intel': { name: 'Live Intelligence', enabled: true, priority: 1 },
  'gdelt-monitor': { name: 'Global Media Intelligence (GDELT)', enabled: true, priority: 1 },
  cascade: { name: 'Infrastructure Cascade', enabled: true, priority: 1 },
  politics: { name: 'World News', enabled: true, priority: 1 },
  us: { name: 'United States', enabled: true, priority: 1 },
  europe: { name: 'Europe', enabled: true, priority: 1 },
  middleeast: { name: 'Middle East', enabled: true, priority: 1 },
  africa: { name: 'Africa', enabled: true, priority: 1 },
  latam: { name: 'Latin America', enabled: true, priority: 1 },
  asia: { name: 'Asia-Pacific', enabled: true, priority: 1 },
  energy: { name: 'Energy & Resources', enabled: true, priority: 1 },
  gov: { name: 'Government', enabled: true, priority: 1 },
  thinktanks: { name: 'Think Tanks', enabled: true, priority: 1 },
  polymarket: { name: 'Predictions', enabled: true, priority: 1 },
  commodities: { name: 'Commodities', enabled: true, priority: 1 },
  markets: { name: 'Markets', enabled: true, priority: 1 },
  economic: { name: 'Economic Indicators', enabled: true, priority: 1 },
  'economic-stress': { name: 'Economic Stress', enabled: true, priority: 2 },
  'federal-register': { name: 'Federal Register', enabled: true, priority: 2 },
  'trade-policy': { name: 'Trade Policy', enabled: true, priority: 1 },
  'trade-disruption': { name: 'Trade Disruption Intelligence', enabled: true, priority: 1 },
  'supply-chain': { name: 'Supply Chain', enabled: true, priority: 1 },
  finance: { name: 'Financial', enabled: true, priority: 1 },
  tech: { name: 'Technology', enabled: true, priority: 2 },
  crypto: { name: 'Crypto', enabled: true, priority: 2 },
  heatmap: { name: 'Sector Heatmap', enabled: true, priority: 2 },
  ai: { name: 'AI/ML', enabled: true, priority: 2 },
  layoffs: { name: 'Layoffs Tracker', enabled: true, priority: 2 },
  monitors: { name: 'My Monitors', enabled: true, priority: 2 },
  'satellite-fires': { name: 'Fires', enabled: true, priority: 2 },
  earthquakes: { name: 'Earthquakes', enabled: true, priority: 2 },
  'cyber-threats': { name: 'Cyber Threats', enabled: true, priority: 2 },
  'threat-inbox': { name: 'Threat Inbox', enabled: true, priority: 2 },
  'local-ids': { name: 'Local IDS', enabled: true, priority: 2 },
  'little-snitch': { name: 'Little Snitch', enabled: true, priority: 2 },
  'comms-health': { name: 'Communications Health', enabled: true, priority: 2 },
  'power-grid': { name: 'Power Grid', enabled: true, priority: 2 },
  'macro-signals': { name: 'Market Radar', enabled: true, priority: 2 },
  'etf-flows': { name: 'BTC ETF Tracker', enabled: true, priority: 2 },
  stablecoins: { name: 'Stablecoins', enabled: true, priority: 2 },
  'ucdp-events': { name: 'UCDP Conflict Events', enabled: true, priority: 2 },
  'nuclear-risk': { name: 'Nuclear Risk Tracker', enabled: true, priority: 2 },  'nuclear-near-miss': { name: 'Nuclear Near-Miss Tracker', enabled: true, priority: 2 },
  'airstrikes': { name: 'Air Strikes & Drones', enabled: true, priority: 2 },
  'strike-package': { name: 'Strike Packages', enabled: true, priority: 2 },
  giving: { name: 'Global Giving', enabled: true, priority: 2 },
  'stoic-reflections': { name: 'Stoic Reflections', enabled: true, priority: 3 },
  'biblical-encouragement': { name: 'Biblical Encouragement', enabled: true, priority: 3 },
  'alan-watts-reflections': { name: 'Alan Watts', enabled: true, priority: 3 },
  'mckenna-visions': { name: 'Terence McKenna', enabled: true, priority: 3 },
  'daily-wisdom': { name: 'Daily Wisdom', enabled: true, priority: 3 },
  displacement: { name: 'UNHCR Displacement', enabled: true, priority: 2 },
  climate: { name: 'Climate Anomalies', enabled: true, priority: 2 },
  'population-exposure': { name: 'Population Exposure', enabled: true, priority: 2 },
  'security-advisories': { name: 'Security Advisories', enabled: true, priority: 2 },
  'cve-tracker': { name: 'CVE Tracker', enabled: true, priority: 2 },
  'vulners-cve': { name: 'Vulners CVE', enabled: true, priority: 2 },
  'bitcoin-abuse': { name: 'Bitcoin Abuse', enabled: true, priority: 2 },
  'reddit-osint': { name: 'Reddit OSINT', enabled: true, priority: 2 },
  'network-rules': { name: 'Network Rules', enabled: true, priority: 3 },
  's2u-intel': { name: 'S2U Intelligence', enabled: true, priority: 1 },
  's2-underground-media': { name: 'S2 Underground', enabled: true, priority: 1 },
  'synthesis': { name: 'Synthesis', enabled: true, priority: 1 },
  'cyber-geo': { name: 'Cyber × Geo', enabled: true, priority: 1 },
  'economic-intel': { name: 'Economic Intel', enabled: true, priority: 1 },
  'oref-sirens': { name: 'Israel Sirens', enabled: true, priority: 2 },
  'telegram-intel': { name: 'Telegram Intel', enabled: true, priority: 2 },
  'space-weather': { name: 'Space Weather', enabled: true, priority: 1 },
  'neo-tracker': { name: 'Near-Earth Objects', enabled: true, priority: 1 },
  'space-security': { name: 'Space Security', enabled: true, priority: 1 },
  'space-superpower': { name: 'Space Superpower', enabled: true, priority: 1 },
  'weather-superpower': { name: 'Weather Intelligence', enabled: true, priority: 1 },
  'spaceflight-news': { name: 'Spaceflight News', enabled: true, priority: 2 },
  'space-launches': { name: 'Space Launches', enabled: true, priority: 2 },
  'disease-outbreaks': { name: 'Disease Outbreaks', enabled: true, priority: 2 },
  'disease-intel': { name: 'Disease Intelligence', enabled: true, priority: 2 },
  'humanitarian-crisis': { name: 'Humanitarian Crises', enabled: true, priority: 2 },
  'air-quality': { name: 'Air Quality', enabled: true, priority: 2 },
  'openaq-monitor': { name: 'Air Quality (OpenAQ)', enabled: true, priority: 2 },
  'mediastack-news': { name: 'News Feed', enabled: true, priority: 1 },
  'wildfire-incidents': { name: 'Wildfires (InciWeb)', enabled: true, priority: 2 },
  'wildfire-intel': { name: 'Wildfire Intel', enabled: true, priority: 1 },
  'hazmat-incidents': { name: 'Hazmat Incidents', enabled: true, priority: 2 },
  'oil-spill': { name: 'Oil & Chemical Spills', enabled: true, priority: 2 },
  'hazard-alerts': { name: 'Hazard Alerts — Near Me', enabled: true, priority: 1 },
  'infrastructure': { name: 'Critical Infrastructure', enabled: true, priority: 2 },
  'grid-intelligence': { name: 'Grid & Internet Intelligence', enabled: true, priority: 1 },
  'infra-risk-matrix': { name: 'Infrastructure Risk Matrix', enabled: true, priority: 1 },
  'earthquake-super': { name: 'Earthquake Intelligence', enabled: true, priority: 1 },
  'seismic-superpower': { name: 'Seismic Intelligence', enabled: true, priority: 1 },
  'cyber-superpower': { name: 'Cyber Intelligence', enabled: true, priority: 1 },
  'cyber-incident-response': { name: 'Cyber Incident Response', enabled: true, priority: 1 },
  'infrastructure-superpower': { name: 'Infrastructure Intelligence', enabled: true, priority: 1 },
  'climate-superpower': { name: 'Climate Intelligence', enabled: true, priority: 1 },
  'evidence-graph': { name: 'Evidence Graph', enabled: true, priority: 1 },
  'gdacs-alerts': { name: 'GDACS Disaster Alerts', enabled: true, priority: 2 },
  'volcano-alerts': { name: 'Volcano Alerts', enabled: true, priority: 2 },
  'nws-alerts': { name: 'NWS Hazard Alerts', enabled: true, priority: 1 },
  'faa-weather-cams': { name: 'FAA Weather Cams', enabled: true, priority: 1 },
  'unified-webcams': { name: 'Webcams', enabled: true, priority: 1 },
  'pinned-webcams': { name: 'Pinned Webcams', enabled: true, priority: 2 },
  'tsunami-alerts': { name: 'Tsunami Alerts', enabled: true, priority: 2 },
  'tropical-cyclones': { name: 'Tropical Cyclones', enabled: true, priority: 2 },
  'food-insecurity': { name: 'Food Insecurity', enabled: true, priority: 2 },
  'offline-maps': { name: 'Offline Maps', enabled: true, priority: 2 },
  'evacuation': { name: 'Evacuation Routes', enabled: true, priority: 2 },
  'family-tracker': { name: 'Family Tracker', enabled: true, priority: 2 },
  'radiation-decay': { name: 'Radiation Decay Calculator', enabled: true, priority: 3 },
  'resource-inventory': { name: 'Resource Inventory', enabled: true, priority: 3 },
  'fear-greed': { name: 'Fear & Greed Index', enabled: true, priority: 2 },
  'internet-disruptions': { name: 'Internet Disruptions', enabled: true, priority: 2 },
  'national-debt': { name: 'National Debt', enabled: true, priority: 2 },
  'sovereign-debt': { name: 'Sovereign Debt', enabled: true, priority: 2 },
  'fuel-prices': { name: 'Fuel Prices', enabled: true, priority: 2 },
  'faa-tfrs': { name: 'FAA TFRs', enabled: true, priority: 2 },
  'air-traffic': { name: 'Air Traffic', enabled: true, priority: 2 },
  'global-weather': { name: 'Global Weather', enabled: true, priority: 1 },
  'opensanctions': { name: 'Global Sanctions & PEP Intelligence', enabled: true, priority: 2 },
  'sanctions-intel': { name: 'OFAC Sanctions Intel', enabled: true, priority: 2 },
  'hibp-breaches': { name: 'HIBP Breaches', enabled: true, priority: 2 },
  'ipinfo-lookup': { name: 'IP Info Lookup', enabled: true, priority: 2 },
  'edgar-filings': { name: 'SEC EDGAR Filings', enabled: true, priority: 2 },
  'isw-reports': { name: 'ISW Situation Reports', enabled: true, priority: 1 },
  'reliefweb-crises': { name: 'UN OCHA Crisis Reports', enabled: true, priority: 1 },
  'bellingcat-osint': { name: 'Bellingcat OSINT', enabled: true, priority: 2 },
  'emsc-seismic': { name: 'Nuclear Test Watch', enabled: true, priority: 1 },
  'fcdo-warnings': { name: 'UK FCDO Warnings', enabled: true, priority: 2 },
  'dfat-warnings': { name: 'Australia DFAT Warnings', enabled: true, priority: 2 },
  'gac-warnings': { name: 'Canada GAC Warnings', enabled: true, priority: 2 },
  'gov-warning-convergence': { name: 'Multi-Gov Consensus Alert', enabled: true, priority: 1 },
  'dod-news': { name: 'Pentagon News', enabled: true, priority: 1 },
  'nato-news': { name: 'NATO Press', enabled: true, priority: 1 },
  'acaps-crises': { name: 'ACAPS Crisis Index', enabled: true, priority: 2 },
  'liveuamap': { name: 'Ukraine Frontline (LiveUA)', enabled: true, priority: 1 },
  'ripe-ncc': { name: 'RIPE NCC BGP', enabled: true, priority: 2 },
  'ripe-atlas': { name: 'RIPE Atlas', enabled: true, priority: 2 },
  'aerospace-reentry': { name: 'Aerospace Reentry Tracker', enabled: true, priority: 2 },
  'satellite-intel': { name: 'Satellite Intel', enabled: true, priority: 2 },
  'amtrak-alerts': { name: 'Amtrak Service Alerts', enabled: true, priority: 2 },
  'avalanche-hazard': { name: 'Avalanche Hazard', enabled: true, priority: 2 },
  'dsca-arms-transfers': { name: 'DSCA Arms Transfers', enabled: true, priority: 2 },
  'dod-contracts': { name: 'DOD Contract Awards', enabled: true, priority: 2 },
  'wikidata-bases': { name: 'Military Bases (WikiData)', enabled: true, priority: 2 },
  'ecdc-surveillance': { name: 'ECDC Disease Surveillance', enabled: true, priority: 2 },
  'fdic-failures': { name: 'FDIC Bank Failures', enabled: true, priority: 2 },
  'habsos': { name: 'Harmful Algal Bloom Watch', enabled: true, priority: 2 },
  'un-security-council': { name: 'UN Security Council', enabled: true, priority: 1 },
  'wildfire-smoke': { name: 'Wildfire Smoke Tracker', enabled: true, priority: 2 },
  'central-bank-calendar': { name: 'Central Bank Calendar', enabled: true, priority: 2 },
  'congress-defense': { name: 'Congress Defense Activity', enabled: true, priority: 2 },
  'combatant-commands': { name: 'Combatant Commands', enabled: true, priority: 1 },
  'foreign-mil-news': { name: 'Foreign Military News', enabled: true, priority: 1 },
  'spc-mesoscale': { name: 'SPC Mesoscale Discussions', enabled: true, priority: 2 },
  'threat-intel-hub': { name: 'Threat Intel Hub', enabled: true, priority: 2 },
  'phishstats-feed': { name: 'PhishStats Feed', enabled: true, priority: 2 },
  'urlscan-threats': { name: 'urlscan.io Threats', enabled: true, priority: 2 },
  'pulsedive-intel': { name: 'Pulsedive Intel', enabled: true, priority: 2 },
  'geo-intel': { name: 'Geo Intel', enabled: true, priority: 2 },
  'dark-web': { name: 'Dark Web', enabled: true, priority: 2 },
  'intelligence-briefing': { name: 'Intelligence Briefing', enabled: true, priority: 1 },
  'ask-crystal-ball': { name: 'Ask Crystal Ball', enabled: true, priority: 1 },
  'survival-advisor': { name: 'Survival Advisor', enabled: true, priority: 1 },
  'threat-synthesis': { name: 'Threat Synthesis', enabled: true, priority: 1 },
  'scenario-simulator': { name: 'Scenario Simulator', enabled: true, priority: 2 },
  'escalation-forecast': { name: 'Escalation Watch', enabled: true, priority: 1 },
  'anomaly-detection': { name: 'Anomaly Detection', enabled: true, priority: 2 },
  'financial-contagion': { name: 'Financial Contagion', enabled: true, priority: 2 },
  'supply-chain-impact': { name: 'Supply Chain Impact', enabled: true, priority: 2 },
  'water-quality': { name: 'Water Quality', enabled: true, priority: 2 },
  'nuclear-monitor': { name: 'Nuclear Monitor', enabled: true, priority: 2 },
  'notification-digest': { name: 'Notification Digest', enabled: true, priority: 1 },
  'notification-history': { name: 'Notification History', enabled: true, priority: 2 },
  'notification-settings': { name: 'Notification Settings', enabled: true, priority: 1 },
  'world-state-comparator': { name: 'World State Comparator', enabled: true, priority: 2 },
  'historical-playback': { name: 'Historical Playback', enabled: true, priority: 2 },
  'personal-relevance': { name: 'Personal Relevance', enabled: true, priority: 1 },
  'situations': { name: 'Situations', enabled: true, priority: 1 },
  'situation-timeline': { name: 'Situation Timeline', enabled: true, priority: 1 },
  'disaster-response': { name: 'Disaster Response', enabled: true, priority: 1 },
  'observation-rules': { name: 'Observation Rules', enabled: true, priority: 1 },
  // Worldview / Palantir / Dragos-inspired panels
  'pattern-of-life': { name: 'Pattern of Life', enabled: true, priority: 2 },
  'sigint-panel': { name: 'SIGINT Monitor', enabled: true, priority: 2 },
  'dark-vessel': { name: 'Dark Vessel Watch', enabled: true, priority: 2 },
  'shadow-fleet': { name: 'Shadow Fleet Tracker', enabled: true, priority: 2 },
  'course-of-action': { name: 'Course of Action', enabled: true, priority: 1 },
  'kill-chain': { name: 'Kill Chain Tracker', enabled: true, priority: 2 },
  'ics-ot-dashboard': { name: 'ICS/OT Dashboard', enabled: true, priority: 2 },
  'ioc-manager': { name: 'IOC Manager', enabled: true, priority: 2 },
  'orbat': { name: 'Order of Battle', enabled: true, priority: 2 },
  'after-action-review': { name: 'After-Action Review', enabled: true, priority: 2 },
  'network-topology': { name: 'Network Topology', enabled: true, priority: 2 },
  'custom-geofence': { name: 'Geofence Alerts', enabled: true, priority: 2 },
  'stix-taxii': { name: 'STIX/TAXII Feeds', enabled: true, priority: 2 },
  // Gotham-advanced intel panels
  'entity-link-graph': { name: 'Entity Link Graph', enabled: true, priority: 2 },
  'timeline-scrubber': { name: 'Timeline Scrubber', enabled: true, priority: 2 },
  'intel-report': { name: 'Intel Reports', enabled: true, priority: 2 },
  'sanctions-crossref': { name: 'Sanctions Cross-Ref', enabled: true, priority: 2 },
  'compound-threat': { name: 'Compound Threats', enabled: true, priority: 2 },
  'correlation-matrix': { name: 'Correlation Matrix', enabled: true, priority: 2 },
  'correlation-map': { name: 'Correlation Map', enabled: true, priority: 2 },
  'strike-packages': { name: 'Strike Packages', enabled: true, priority: 2 },
  'api-diagnostic': { name: 'API Diagnostic', enabled: true, priority: 3 },
  'feed-health': { name: 'Feed Health', enabled: true, priority: 2 },
  'feed-health-dashboard': { name: 'Feed Health Dashboard', enabled: true, priority: 2 },
  'alert-fatigue-dashboard': { name: 'Alert Fatigue', enabled: true, priority: 2 },
  'threat-convergence': { name: 'Threat Convergence', enabled: true, priority: 1 },
  'geopolitical-risk': { name: 'Geopolitical Risk', enabled: true, priority: 1 },
  'sanctions-tracker': { name: 'Sanctions Tracker', enabled: true, priority: 1 },
  'currency-warfare': { name: 'Currency Warfare', enabled: true, priority: 1 },
  'economic-coercion': { name: 'Economic Coercion', enabled: true, priority: 1 },
  'system-diagnostic': { name: 'System Diagnostic', enabled: true, priority: 1 },
  'self-test': { name: 'Self-Test', enabled: true, priority: 2 },
  'operator-mode': { name: 'Operator Mode', enabled: true, priority: 2 },
  'global-risk-heatmap': { name: 'Global Risk Heatmap', enabled: true, priority: 1 },
  'command-center': { name: 'Command Center', enabled: true, priority: 1 },
  'algorithm-diagnostic': { name: 'Algorithm Diagnostic', enabled: true, priority: 3 },
  'source-confidence': { name: 'Source Confidence', enabled: true, priority: 2 },
  'event-store': { name: 'Event Store', enabled: true, priority: 3 },
  'belief-calibration': { name: 'Belief Calibration', enabled: true, priority: 3 },
  'outcome-ledger': { name: 'Outcome Ledger', enabled: true, priority: 3 },
  'bias-detection': { name: 'Bias Detection', enabled: true, priority: 2 },
  'contradiction-detector': { name: 'Contradictions', enabled: true, priority: 2 },
  'active-learning': { name: 'Active Learning', enabled: true, priority: 2 },
  'improvement-scheduler': { name: 'Improvement Scheduler', enabled: true, priority: 3 },
  'model-governance': { name: 'Model Governance', enabled: true, priority: 3 },
  'algo-eval': { name: 'Algorithm Evaluation', enabled: true, priority: 3 },
  'backtest': { name: 'Backtest Gate', enabled: true, priority: 3 },
  'shadow-mode': { name: 'Shadow Algorithms', enabled: true, priority: 3 },

  'shadow-comparison': { name: 'Shadow A/B Comparison', enabled: true, priority: 3 },
  'cognitive-bias-detector': { name: 'Cognitive Bias Detector', enabled: true, priority: 3 },
  'crisis-signature': { name: 'Crisis Signature Library', enabled: true, priority: 2 },
  'predictive-crisis-index': { name: 'Predictive Crisis Index', enabled: true, priority: 1 },
  'collection-gap': { name: 'Collection Gap Discovery', enabled: true, priority: 2 },
  'safety-case': { name: 'Safety Case', enabled: true, priority: 1 },
  'multi-agent-review': { name: 'Multi-Agent Review', enabled: true, priority: 2 },
  'repair-recommendations': { name: 'Repair Recommendations', enabled: true, priority: 2 },
  'mission-ledger-bridge': { name: 'Mission Ledger Bridge', enabled: true, priority: 2 },
  'counterfactual-replay': { name: 'Counterfactual Replay', enabled: true, priority: 2 },
  'alert-trace': { name: 'Alert Trace', enabled: true, priority: 2 },
  'alert-rules-tuning': { name: 'Alert Rules', enabled: true, priority: 2 },
  'intelligence-quality-debt': { name: 'Intelligence Quality', enabled: true, priority: 2 },
  'supply-chain-resilience': { name: 'Supply Chain Resilience', enabled: true, priority: 2 },
  'scenario-replay': { name: 'Scenario Replay', enabled: true, priority: 3 },
  'playbook': { name: 'Response Playbooks', enabled: true, priority: 2 },
  'cross-domain-contradiction-detector': { name: 'Cross-Domain Conflicts', enabled: true, priority: 2 },
  'aviation-intel': { name: 'Aviation Intel', enabled: true, priority: 2 },
  'aviation-superpower': { name: 'Aviation Superpower', enabled: true, priority: 2 },
  'nuclear-superpower': { name: 'Nuclear Intelligence', enabled: true, priority: 1 },
  'energy-superpower': { name: 'Energy Intelligence', enabled: true, priority: 2 },
  'geopolitical-superpower': { name: 'Geopolitical Superpower', enabled: true, priority: 1 },
  'critical-minerals': { name: 'Critical Minerals', enabled: true, priority: 2 },
  'financial-superpower': { name: 'Financial Superpower', enabled: true, priority: 1 },
  'regulatory-arbitrage': { name: 'Regulatory Arbitrage', enabled: true, priority: 1 },
  'political-risk-superpower': { name: 'Political Risk Intelligence', enabled: true, priority: 1 },
  'state-fragility': { name: 'State Fragility', enabled: true, priority: 1 },
  'state-capacity': { name: 'State Capacity', enabled: true, priority: 1 },
  'global-migration-crisis': { name: 'Migration Crisis Intelligence', enabled: true, priority: 1 },
  'organized-crime-superpower': { name: 'Organized Crime Intelligence', enabled: true, priority: 1 },
  'narcotics-trafficking': { name: 'Narcotics Trafficking', enabled: true, priority: 1 },
  'terrorism-superpower': { name: 'Terrorism Intelligence', enabled: true, priority: 1 },
  'water-security': { name: 'Water Security Intelligence', enabled: true, priority: 1 },
  'energy-security': { name: 'Energy Security Intelligence', enabled: true, priority: 1 },
  'arms-proliferation': { name: 'Arms Proliferation Monitor', enabled: true, priority: 1 },
  'space-militarization': { name: 'Space Militarization Monitor', enabled: true, priority: 1 },
  'arctic-monitoring': { name: 'Arctic Intelligence', enabled: true, priority: 1 },
  'climate-security-nexus': { name: 'Climate-Security Nexus', enabled: true, priority: 1 },
  'arctic-competition': { name: 'Arctic Competition', enabled: true, priority: 1 },
  'great-power-competition': { name: 'Great Power Competition', enabled: true, priority: 1 },
  'cyber-espionage': { name: 'Cyber Espionage Tracker', enabled: true, priority: 1 },
  'urban-instability': { name: 'Urban Instability Monitor', enabled: true, priority: 1 },
  'political-economy': { name: 'Political Economy Risk', enabled: true, priority: 1 },
  'state-capitalism': { name: 'State Capitalism', enabled: true, priority: 1 },
  'election-monitoring': { name: 'Election Monitoring', enabled: true, priority: 1 },
  'urban-security': { name: 'Urban Security', enabled: true, priority: 1 },
  'signal-noise-filter': { name: 'Signal Quality', enabled: true, priority: 1 },
  'alliance-cohesion': { name: 'Alliance Cohesion', enabled: true, priority: 1 },
  'information-operations': { name: 'Information Operations', enabled: true, priority: 1 },
  'maritime-boundary': { name: 'Maritime Boundary', enabled: true, priority: 1 },
  'tech-competition': { name: 'Tech Competition', enabled: true, priority: 1 },
  'shortage-radar': { name: 'Shortage Radar', enabled: true, priority: 1 },
  'storm-posture': { name: 'Storm Posture', enabled: true, priority: 1 },
  'shortage-detail-wheat': { name: 'Wheat Shortage', enabled: true, priority: 2 },
  'shortage-detail-corn': { name: 'Corn Shortage', enabled: true, priority: 2 },
  'shortage-detail-rice': { name: 'Rice Shortage', enabled: true, priority: 2 },
  'shortage-detail-soybeans': { name: 'Soybeans Shortage', enabled: true, priority: 2 },
  'shortage-detail-diesel': { name: 'Diesel Shortage', enabled: true, priority: 2 },
  'shortage-detail-gasoline': { name: 'Gasoline Shortage', enabled: true, priority: 2 },
  'shortage-detail-natural-gas': { name: 'Natural Gas Shortage', enabled: true, priority: 2 },
  'shortage-detail-jet-fuel': { name: 'Jet Fuel Shortage', enabled: true, priority: 2 },
  'weather-hazard': { name: 'Weather Hazards', enabled: true, priority: 1 },
  'cascade-simulator': { name: 'Cascade Simulator', enabled: true, priority: 2 },
  'emergency-broadcast': { name: 'Emergency Broadcasts', enabled: true, priority: 2 },
  'satellite-change': { name: 'Satellite Change Detection', enabled: true, priority: 2 },
  'extended-forecast': { name: '7-Day Forecast', enabled: true, priority: 1 },
  'tide-predictions': { name: 'Tide Predictions', enabled: true, priority: 2 },
  'pollen': { name: 'Pollen & Allergy', enabled: true, priority: 1 },
  'weather-radar': { name: 'Weather Radar', enabled: true, priority: 1 },
  'goes-satellite': { name: 'GOES Satellite', enabled: true, priority: 1 },
  'flood-monitor': { name: 'Flood Monitor', enabled: true, priority: 1 },
  'volcano-monitor': { name: 'Volcano Monitor', enabled: true, priority: 2 },
  'severe-weather': { name: 'Severe Weather / SPC', enabled: true, priority: 1 },
  'shakealert': { name: 'ShakeAlert + ShakeMaps', enabled: true, priority: 2 },
  'sms-command-interface': { name: 'SMS Command Interface', enabled: true, priority: 3 },
  'what-changed': { name: 'What Changed', enabled: true, priority: 2 },
  'counterterrorism': { name: 'Counterterrorism Monitor', enabled: true, priority: 1 },
  'extremism-tracking': { name: 'Extremism Tracking', enabled: true, priority: 1 },
  'territorial-disputes': { name: 'Territorial Disputes Tracker', enabled: true, priority: 1 },
  'regime-stability': { name: 'Regime Stability', enabled: true, priority: 1 },
  'coup-risk': { name: 'Coup Risk Monitor', enabled: true, priority: 1 },
  'arms-sales': { name: 'Arms Sales', enabled: true, priority: 1 },
  'firms-thermal': { name: 'Thermal Anomalies (FIRMS)', enabled: true, priority: 1 },
  'global-logistics-chokepoints': { name: 'Global Logistics Chokepoints', enabled: true, priority: 1 },
  'coalition-dynamics': { name: 'Coalition Dynamics', enabled: true, priority: 1 },
  'transnational-repression': { name: 'Transnational Repression', enabled: true, priority: 1 },
  'corruption-index': { name: 'Corruption Index', enabled: true, priority: 1 },
  'maritime-piracy': { name: 'Maritime Piracy', enabled: true, priority: 1 },
  'political-violence': { name: 'Political Violence Tracker', enabled: true, priority: 1 },
  'electric-grid-vulnerability': { name: 'Electric Grid Vulnerability', enabled: true, priority: 1 },
  // Consolidated from PRs 789–950
  'conflict-escalation': { name: 'Conflict Escalation Monitor', enabled: true, priority: 1 },
  'insurgency-tracker': { name: 'Insurgency Tracker', enabled: true, priority: 1 },
  'nuclear-nonproliferation': { name: 'Nuclear Nonproliferation', enabled: true, priority: 2 },
  'food-systems-geopolitics': { name: 'Food Systems & Geopolitics', enabled: true, priority: 1 },
  'drone-warfare': { name: 'Drone Warfare Monitor', enabled: true, priority: 1 },
  'space-debris': { name: 'Space Debris Tracker', enabled: true, priority: 1 },
  'border-incidents': { name: 'Border Incidents', enabled: true, priority: 1 },
  'disinformation-networks': { name: 'Disinformation Networks', enabled: true, priority: 1 },
  'warlord-economics': { name: 'Warlord Economics', enabled: true, priority: 1 },
  'ai-governance': { name: 'AI Governance', enabled: true, priority: 1 },
  'cyber-norms': { name: 'Cyber Norms & Governance', enabled: true, priority: 1 },
  'digital-currency-geopolitics': { name: 'Digital Currency Geopolitics', enabled: true, priority: 1 },
  'foreign-aid-weaponization': { name: 'Foreign Aid Weaponization', enabled: true, priority: 1 },
  'debt-trap-diplomacy': { name: 'Debt Trap Diplomacy', enabled: true, priority: 2 },
  'media-freedom': { name: 'Media Freedom', enabled: true, priority: 1 },
  'military-exercises': { name: 'Military Exercises Monitor', enabled: true, priority: 1 },
  'hostage-diplomacy': { name: 'Hostage Diplomacy Tracker', enabled: true, priority: 1 },
  'sovereign-wealth-funds': { name: 'Sovereign Wealth Funds', enabled: true, priority: 1 },
  'tech-transfer-risk': { name: 'Tech Transfer Risk', enabled: true, priority: 1 },
  'global-military-spending': { name: 'Global Military Spending', enabled: true, priority: 1 },
  'foreign-fighters': { name: 'Foreign Fighters Monitor', enabled: true, priority: 1 },
  'escalation-ladder': { name: 'Escalation Ladder', enabled: true, priority: 1 },
  'resource-nationalism': { name: 'Resource Nationalism', enabled: true, priority: 1 },
  'coercive-diplomacy': { name: 'Coercive Diplomacy', enabled: true, priority: 1 },
  'diplomatic-signals': { name: 'Diplomatic Signals', enabled: true, priority: 1 },
  'treaty-surveillance': { name: 'Treaty Surveillance', enabled: true, priority: 1 },
  'seabed-warfare': { name: 'Seabed Warfare', enabled: true, priority: 1 },
  'intl-law-violations': { name: 'International Law Violations', enabled: true, priority: 1 },
  'intelligence-cooperation': { name: 'Intelligence Cooperation', enabled: true, priority: 1 },
  'energy-weaponization': { name: 'Energy Weaponization', enabled: true, priority: 1 },
  'propaganda-tracking': { name: 'Propaganda Tracking', enabled: true, priority: 1 },
  'digital-autocracy': { name: 'Digital Autocracy', enabled: true, priority: 1 },
  'foreign-investment-risk': { name: 'Foreign Investment Risk Monitor', enabled: true, priority: 1 },
  'gray-zone-conflict': { name: 'Gray Zone Conflict Tracker', enabled: true, priority: 1 },
  'nuclear-deterrence': { name: 'Nuclear Deterrence Monitor', enabled: true, priority: 1 },
  'travel-safety': { name: 'Travel Safety Monitor', enabled: true, priority: 1 },
  'global-conflict': { name: 'Global Conflicts', enabled: true, priority: 1 },
  'strategic-deception': { name: 'Strategic Deception Tracker', enabled: true, priority: 1 },
  'economic-espionage': { name: 'Economic Espionage Tracker', enabled: true, priority: 1 },
  'space-weaponization': { name: 'Space Weaponization Tracker', enabled: true, priority: 1 },
  'psychological-operations': { name: 'Psychological Operations Monitor', enabled: true, priority: 1 },
  'mercenary-ecosystem': { name: 'Mercenary Ecosystem Tracker', enabled: true, priority: 1 },
  'quantum-tech-race': { name: 'Quantum Technology Race', enabled: true, priority: 1 },
  'semiconductor-geopolitics': { name: 'Semiconductor Geopolitics', enabled: true, priority: 1 },
  'election-interference': { name: 'Election Interference Tracker', enabled: true, priority: 1 },
  'migration-crisis': { name: 'Migration Crisis Monitor', enabled: true, priority: 1 },
  'organized-crime': { name: 'Organized Crime Networks', enabled: true, priority: 1 },
  'human-rights-abuses': { name: 'Human Rights Abuses', enabled: true, priority: 1 },
  'energy-geopolitics': { name: 'Energy Geopolitics', enabled: true, priority: 1 },
  'sovereign-debt-crisis': { name: 'Sovereign Debt Crisis Monitor', enabled: true, priority: 1 },
  'pandemic-preparedness': { name: 'Pandemic Preparedness', enabled: true, priority: 2 },
  'critical-infra-attack': { name: 'Critical Infrastructure Attacks', enabled: true, priority: 2 },
  'democratic-backsliding': { name: 'Democratic Backsliding', enabled: true, priority: 1 },
  'financial-crimes': { name: 'Financial Crimes', enabled: true, priority: 1 },
  'private-military': { name: 'Private Military Monitor', enabled: true, priority: 1 },
  'hybrid-warfare': { name: 'Hybrid Warfare Monitor', enabled: true, priority: 1 },
  'resource-competition': { name: 'Resource Competition', enabled: true, priority: 2 },
  'diplomatic-crisis': { name: 'Diplomatic Crisis', enabled: true, priority: 1 },
  'digital-infrastructure': { name: 'Digital Infrastructure', enabled: true, priority: 1 },
  'global-health-security': { name: 'Global Health Security', enabled: true, priority: 1 },
  'food-security-superpower': { name: 'Food Security Intelligence', enabled: true, priority: 1 },
  'datacenter-readiness': { name: 'Data Center Readiness', enabled: true, priority: 1 },
};

const FULL_MAP_LAYERS: MapLayers = {
  iranAttacks: true,
  gpsJamming: false,
  conflicts: true,
  bases: true,
  cables: false,
  pipelines: false,
  hotspots: true,
  ais: false,
  nuclear: true,
  irradiators: false,
  sanctions: true,
  weather: true,
  economic: true,
  waterways: true,
  outages: true,
  cyberThreats: true,
  datacenters: false,
  protests: false,
  flights: false,
  military: true,
  natural: true,
  spaceports: false,
  minerals: false,
  fires: false,
  // Data source layers
  ucdpEvents: true,
  airstrikes: true,
  strikePackages: true,
  displacement: true,
  climate: false,
  // Tech layers (disabled in full variant)
  startupHubs: false,
  cloudRegions: false,
  accelerators: false,
  techHQs: false,
  techEvents: false,
  // Finance layers (disabled in full variant)
  stockExchanges: false,
  financialCenters: false,
  centralBanks: false,
  commodityHubs: false,
  gulfInvestments: false,
  // Happy variant layers
  positiveEvents: false,
  kindness: false,
  happiness: false,
  speciesRecovery: false,
  renewableInstallations: false,
  tradeRoutes: true,
  s2pimu: false,
  dayNight: true,
  faaWeatherCams: true,
  adsb: false,
  acledEvents: false,
  militaryFlights: false,
  aviationIntel: true,
  diseaseIntel: false,
  forecastOverlay: true,
  theaterPolygons: true,
  convergenceRings: true,
  threatHeatmap: false,
  sigintConvergence: true,
  // Weather overlay layers — radar on by default so users see
  // precipitation tiles out of the box without hunting for the toggle.
  weatherRadar: true,
  weatherSatellite: false,
  lightning: false,
  owmTemperature: false,
  owmPrecipitation: false,
  owmClouds: false,
  owmWind: false,
  redFlagWarnings: true,
  weatherHazards: true,
  wastewaterStates: true,  buildings3d: true,
  satellites: false,
  aircraft3d: false,
  streetTiles: false,
  navigationRoute: false,
  volcanoMonitor: true,
  severeWeatherPolygons: true,
  shakemapOverlay: false,
};

const FULL_MOBILE_MAP_LAYERS: MapLayers = {
  iranAttacks: true,
  gpsJamming: false,
  conflicts: true,
  bases: false,
  cables: false,
  pipelines: false,
  hotspots: true,
  ais: false,
  nuclear: false,
  irradiators: false,
  sanctions: true,
  weather: true,
  economic: false,
  waterways: false,
  outages: true,
  cyberThreats: false,
  datacenters: false,
  protests: false,
  flights: false,
  military: false,
  natural: true,
  spaceports: false,
  minerals: false,
  fires: false,
  // Data source layers
  ucdpEvents: false,
  airstrikes: false,
  strikePackages: false,
  displacement: false,
  climate: false,
  // Tech layers (disabled in full variant)
  startupHubs: false,
  cloudRegions: false,
  accelerators: false,
  techHQs: false,
  techEvents: false,
  // Finance layers (disabled in full variant)
  stockExchanges: false,
  financialCenters: false,
  centralBanks: false,
  commodityHubs: false,
  gulfInvestments: false,
  // Happy variant layers
  positiveEvents: false,
  kindness: false,
  happiness: false,
  speciesRecovery: false,
  renewableInstallations: false,
  tradeRoutes: false,
  s2pimu: false,
  dayNight: false,
  faaWeatherCams: false,
  adsb: false,
  acledEvents: false,
  militaryFlights: false,
  aviationIntel: true,
  diseaseIntel: false,
  forecastOverlay: false,
  theaterPolygons: false,
  convergenceRings: false,
  threatHeatmap: false,
  sigintConvergence: false,
  weatherRadar: false,
  weatherSatellite: false,
  lightning: false,
  owmTemperature: false,
  owmPrecipitation: false,
  owmClouds: false,
  owmWind: false,
  redFlagWarnings: false,
  weatherHazards: false,
  wastewaterStates: false,
  buildings3d: false,  satellites: false,
  aircraft3d: false,
  streetTiles: false,
  navigationRoute: false,
  volcanoMonitor: false,
  severeWeatherPolygons: false,
  shakemapOverlay: false,
};

// ============================================
// TECH VARIANT (Tech/AI/Startups)
// ============================================
const TECH_PANELS: Record<string, PanelConfig> = {
  map: { name: 'Global Tech Map', enabled: true, priority: 1 },
  insights: { name: 'AI Insights', enabled: true, priority: 1 },
  regulation: { name: 'AI Regulation Dashboard', enabled: true, priority: 1 },
  'tech-readiness': { name: 'Tech Readiness Index', enabled: true, priority: 1 },
  ai: { name: 'AI/ML News', enabled: true, priority: 1 },
  'tech-hubs': { name: 'Hot Tech Hubs', enabled: true, priority: 1 },
  tech: { name: 'Technology', enabled: true, priority: 1 },
  policy: { name: 'AI Policy & Regulation', enabled: true, priority: 1 },
  'live-news': { name: 'Tech Headlines', enabled: true, priority: 1 },
  'live-webcams': { name: 'Live Webcams', enabled: true, priority: 2 },
  startups: { name: 'Startups & VC', enabled: true, priority: 1 },
  vcblogs: { name: 'VC Insights & Essays', enabled: true, priority: 1 },
  regionalStartups: { name: 'Global Startup News', enabled: true, priority: 1 },
  unicorns: { name: 'Unicorn Tracker', enabled: true, priority: 1 },
  accelerators: { name: 'Accelerators & Demo Days', enabled: true, priority: 1 },
  security: { name: 'Cybersecurity', enabled: true, priority: 1 },
  layoffs: { name: 'Layoffs Tracker', enabled: true, priority: 1 },
  markets: { name: 'Tech Stocks', enabled: true, priority: 2 },
  finance: { name: 'Financial News', enabled: true, priority: 2 },
  crypto: { name: 'Crypto', enabled: true, priority: 2 },
  hardware: { name: 'Semiconductors & Hardware', enabled: true, priority: 2 },
  cloud: { name: 'Cloud & Infrastructure', enabled: true, priority: 2 },
  dev: { name: 'Developer Community', enabled: true, priority: 2 },
  github: { name: 'GitHub Trending', enabled: true, priority: 1 },
  ipo: { name: 'IPO & SPAC', enabled: true, priority: 2 },
  polymarket: { name: 'Tech Predictions', enabled: true, priority: 2 },
  funding: { name: 'Funding & VC', enabled: true, priority: 1 },
  producthunt: { name: 'Product Hunt', enabled: true, priority: 1 },
  events: { name: 'Tech Events', enabled: true, priority: 1 },
  'service-status': { name: 'Service Status', enabled: true, priority: 2 },
  economic: { name: 'Economic Indicators', enabled: true, priority: 2 },
  'macro-signals': { name: 'Market Radar', enabled: true, priority: 2 },
  'etf-flows': { name: 'BTC ETF Tracker', enabled: true, priority: 2 },
  stablecoins: { name: 'Stablecoins', enabled: true, priority: 2 },
  monitors: { name: 'My Monitors', enabled: true, priority: 2 },
};

const TECH_MAP_LAYERS: MapLayers = {
  gpsJamming: false,
  conflicts: false,
  bases: false,
  cables: true,
  pipelines: false,
  hotspots: false,
  ais: false,
  nuclear: false,
  irradiators: false,
  sanctions: false,
  weather: true,
  economic: true,
  waterways: false,
  outages: true,
  cyberThreats: false,
  datacenters: true,
  protests: false,
  flights: false,
  military: false,
  natural: true,
  spaceports: false,
  minerals: false,
  fires: false,
  // Data source layers
  ucdpEvents: false,
  airstrikes: false,
  strikePackages: false,
  displacement: false,
  climate: false,
  // Tech layers (enabled in tech variant)
  startupHubs: true,
  cloudRegions: true,
  accelerators: false,
  techHQs: true,
  techEvents: true,
  // Finance layers (disabled in tech variant)
  stockExchanges: false,
  financialCenters: false,
  centralBanks: false,
  commodityHubs: false,
  gulfInvestments: false,
  // Happy variant layers
  positiveEvents: false,
  kindness: false,
  happiness: false,
  speciesRecovery: false,
  renewableInstallations: false,
  tradeRoutes: false,
  iranAttacks: false,
  s2pimu: false,
  dayNight: false,
  faaWeatherCams: false,
  adsb: false,
  acledEvents: false,
  militaryFlights: false,
  aviationIntel: false,
  diseaseIntel: false,
  forecastOverlay: false,
  theaterPolygons: false,
  convergenceRings: false,
  threatHeatmap: false,
  sigintConvergence: false,
  weatherRadar: false,
  weatherSatellite: false,
  lightning: false,
  owmTemperature: false,
  owmPrecipitation: false,
  owmClouds: false,
  owmWind: false,
  redFlagWarnings: false,
  weatherHazards: false,
  wastewaterStates: false,
  buildings3d: false,  satellites: false,
  aircraft3d: false,
  streetTiles: false,
  navigationRoute: false,
  volcanoMonitor: false,
  severeWeatherPolygons: false,
  shakemapOverlay: false,
};

const TECH_MOBILE_MAP_LAYERS: MapLayers = {
  gpsJamming: false,
  conflicts: false,
  bases: false,
  cables: false,
  pipelines: false,
  hotspots: false,
  ais: false,
  nuclear: false,
  irradiators: false,
  sanctions: false,
  weather: false,
  economic: false,
  waterways: false,
  outages: true,
  cyberThreats: false,
  datacenters: true,
  protests: false,
  flights: false,
  military: false,
  natural: true,
  spaceports: false,
  minerals: false,
  fires: false,
  // Data source layers
  ucdpEvents: false,
  airstrikes: false,
  strikePackages: false,
  displacement: false,
  climate: false,
  // Tech layers (limited on mobile)
  startupHubs: true,
  cloudRegions: false,
  accelerators: false,
  techHQs: false,
  techEvents: true,
  // Finance layers (disabled in tech variant)
  stockExchanges: false,
  financialCenters: false,
  centralBanks: false,
  commodityHubs: false,
  gulfInvestments: false,
  // Happy variant layers
  positiveEvents: false,
  kindness: false,
  happiness: false,
  speciesRecovery: false,
  renewableInstallations: false,
  tradeRoutes: false,
  iranAttacks: false,
  s2pimu: false,
  dayNight: false,
  faaWeatherCams: false,
  adsb: false,
  acledEvents: false,
  militaryFlights: false,
  aviationIntel: false,
  diseaseIntel: false,
  forecastOverlay: false,
  theaterPolygons: false,
  convergenceRings: false,
  threatHeatmap: false,
  sigintConvergence: false,
  weatherRadar: false,
  weatherSatellite: false,
  lightning: false,
  owmTemperature: false,
  owmPrecipitation: false,
  owmClouds: false,
  owmWind: false,
  redFlagWarnings: false,
  weatherHazards: false,
  wastewaterStates: false,
  buildings3d: false,  satellites: false,
  aircraft3d: false,
  streetTiles: false,
  navigationRoute: false,
  volcanoMonitor: false,
  severeWeatherPolygons: false,
  shakemapOverlay: false,
};

// ============================================
// FINANCE VARIANT (Markets/Trading)
// ============================================
const FINANCE_PANELS: Record<string, PanelConfig> = {
  map: { name: 'Global Markets Map', enabled: true, priority: 1 },
  'live-news': { name: 'Market Headlines', enabled: true, priority: 1 },
  'live-webcams': { name: 'Live Webcams', enabled: true, priority: 2 },
  insights: { name: 'AI Market Insights', enabled: true, priority: 1 },
  markets: { name: 'Live Markets', enabled: true, priority: 1 },
  'markets-news': { name: 'Markets News', enabled: true, priority: 2 },
  forex: { name: 'Forex & Currencies', enabled: true, priority: 1 },
  bonds: { name: 'Fixed Income', enabled: true, priority: 1 },
  commodities: { name: 'Commodities & Futures', enabled: true, priority: 1 },
  'commodities-news': { name: 'Commodities News', enabled: true, priority: 2 },
  crypto: { name: 'Crypto & Digital Assets', enabled: true, priority: 1 },
  'crypto-news': { name: 'Crypto News', enabled: true, priority: 2 },
  centralbanks: { name: 'Central Bank Watch', enabled: true, priority: 1 },
  economic: { name: 'Economic Data', enabled: true, priority: 1 },
  'trade-policy': { name: 'Trade Policy', enabled: true, priority: 1 },
  'supply-chain': { name: 'Supply Chain', enabled: true, priority: 1 },
  'economic-news': { name: 'Economic News', enabled: true, priority: 2 },
  ipo: { name: 'IPOs, Earnings & M&A', enabled: true, priority: 1 },
  heatmap: { name: 'Sector Heatmap', enabled: true, priority: 1 },
  'macro-signals': { name: 'Market Radar', enabled: true, priority: 1 },
  derivatives: { name: 'Derivatives & Options', enabled: true, priority: 2 },
  fintech: { name: 'Fintech & Trading Tech', enabled: true, priority: 2 },
  regulation: { name: 'Financial Regulation', enabled: true, priority: 2 },
  institutional: { name: 'Hedge Funds & PE', enabled: true, priority: 2 },
  analysis: { name: 'Market Analysis', enabled: true, priority: 2 },
  'etf-flows': { name: 'BTC ETF Tracker', enabled: true, priority: 2 },
  stablecoins: { name: 'Stablecoins', enabled: true, priority: 2 },
  'gcc-investments': { name: 'GCC Investments', enabled: true, priority: 2 },
  gccNews: { name: 'GCC Business News', enabled: true, priority: 2 },
  polymarket: { name: 'Predictions', enabled: true, priority: 2 },
  monitors: { name: 'My Monitors', enabled: true, priority: 2 },
};

const FINANCE_MAP_LAYERS: MapLayers = {
  gpsJamming: false,
  conflicts: false,
  bases: false,
  cables: true,
  pipelines: true,
  hotspots: false,
  ais: false,
  nuclear: false,
  irradiators: false,
  sanctions: true,
  weather: true,
  economic: true,
  waterways: true,
  outages: true,
  cyberThreats: false,
  datacenters: false,
  protests: false,
  flights: false,
  military: false,
  natural: true,
  spaceports: false,
  minerals: false,
  fires: false,
  // Data source layers
  ucdpEvents: false,
  airstrikes: false,
  strikePackages: false,
  displacement: false,
  climate: false,
  // Tech layers (disabled in finance variant)
  startupHubs: false,
  cloudRegions: false,
  accelerators: false,
  techHQs: false,
  techEvents: false,
  // Finance layers (enabled in finance variant)
  stockExchanges: true,
  financialCenters: true,
  centralBanks: true,
  commodityHubs: false,
  gulfInvestments: false,
  // Happy variant layers
  positiveEvents: false,
  kindness: false,
  happiness: false,
  speciesRecovery: false,
  renewableInstallations: false,
  tradeRoutes: true,
  iranAttacks: false,
  s2pimu: false,
  dayNight: false,
  faaWeatherCams: false,
  adsb: false,
  acledEvents: false,
  militaryFlights: false,
  aviationIntel: false,
  diseaseIntel: false,
  forecastOverlay: false,
  theaterPolygons: false,
  convergenceRings: false,
  threatHeatmap: false,
  sigintConvergence: false,
  weatherRadar: false,
  weatherSatellite: false,
  lightning: false,
  owmTemperature: false,
  owmPrecipitation: false,
  owmClouds: false,
  owmWind: false,
  redFlagWarnings: false,
  weatherHazards: false,
  wastewaterStates: false,
  buildings3d: false,  satellites: false,
  aircraft3d: false,
  streetTiles: false,
  navigationRoute: false,
  volcanoMonitor: false,
  severeWeatherPolygons: false,
  shakemapOverlay: false,
};

const FINANCE_MOBILE_MAP_LAYERS: MapLayers = {
  gpsJamming: false,
  conflicts: false,
  bases: false,
  cables: false,
  pipelines: false,
  hotspots: false,
  ais: false,
  nuclear: false,
  irradiators: false,
  sanctions: false,
  weather: false,
  economic: true,
  waterways: false,
  outages: true,
  cyberThreats: false,
  datacenters: false,
  protests: false,
  flights: false,
  military: false,
  natural: true,
  spaceports: false,
  minerals: false,
  fires: false,
  // Data source layers
  ucdpEvents: false,
  airstrikes: false,
  strikePackages: false,
  displacement: false,
  climate: false,
  // Tech layers (disabled)
  startupHubs: false,
  cloudRegions: false,
  accelerators: false,
  techHQs: false,
  techEvents: false,
  // Finance layers (limited on mobile)
  stockExchanges: true,
  financialCenters: false,
  centralBanks: true,
  commodityHubs: false,
  gulfInvestments: false,
  // Happy variant layers
  positiveEvents: false,
  kindness: false,
  happiness: false,
  speciesRecovery: false,
  renewableInstallations: false,
  tradeRoutes: false,
  iranAttacks: false,
  s2pimu: false,
  dayNight: false,
  faaWeatherCams: false,
  adsb: false,
  acledEvents: false,
  militaryFlights: false,
  aviationIntel: false,
  diseaseIntel: false,
  forecastOverlay: false,
  theaterPolygons: false,
  convergenceRings: false,
  threatHeatmap: false,
  sigintConvergence: false,
  weatherRadar: false,
  weatherSatellite: false,
  lightning: false,
  owmTemperature: false,
  owmPrecipitation: false,
  owmClouds: false,
  owmWind: false,
  redFlagWarnings: false,
  weatherHazards: false,
  wastewaterStates: false,
  buildings3d: false,  satellites: false,
  aircraft3d: false,
  streetTiles: false,
  navigationRoute: false,
  volcanoMonitor: false,
  severeWeatherPolygons: false,
  shakemapOverlay: false,
};

// ============================================
// HAPPY VARIANT (Good News & Progress)
// ============================================
const HAPPY_PANELS: Record<string, PanelConfig> = {
  map: { name: 'World Map', enabled: true, priority: 1 },
  'positive-feed': { name: 'Good News Feed', enabled: true, priority: 1 },
  progress: { name: 'Human Progress', enabled: true, priority: 1 },
  counters: { name: 'Live Counters', enabled: true, priority: 1 },
  spotlight: { name: "Today's Hero", enabled: true, priority: 1 },
  breakthroughs: { name: 'Breakthroughs', enabled: true, priority: 1 },
  digest: { name: '5 Good Things', enabled: true, priority: 1 },
  species: { name: 'Conservation Wins', enabled: true, priority: 1 },
  renewable: { name: 'Renewable Energy', enabled: true, priority: 1 },
  giving: { name: 'Global Giving', enabled: true, priority: 1 },
};

const HAPPY_MAP_LAYERS: MapLayers = {
  gpsJamming: false,
  conflicts: false,
  bases: false,
  cables: false,
  pipelines: false,
  hotspots: false,
  ais: false,
  nuclear: false,
  irradiators: false,
  sanctions: false,
  weather: false,
  economic: false,
  waterways: false,
  outages: false,
  cyberThreats: false,
  datacenters: false,
  protests: false,
  flights: false,
  military: false,
  natural: false,
  spaceports: false,
  minerals: false,
  fires: false,
  // Data source layers
  ucdpEvents: false,
  airstrikes: false,
  strikePackages: false,
  displacement: false,
  climate: false,
  // Tech layers (disabled)
  startupHubs: false,
  cloudRegions: false,
  accelerators: false,
  techHQs: false,
  techEvents: false,
  // Finance layers (disabled)
  stockExchanges: false,
  financialCenters: false,
  centralBanks: false,
  commodityHubs: false,
  gulfInvestments: false,
  // Happy variant layers
  positiveEvents: true,
  kindness: true,
  happiness: true,
  speciesRecovery: true,
  renewableInstallations: true,
  tradeRoutes: false,
  iranAttacks: false,
  s2pimu: false,
  dayNight: false,
  faaWeatherCams: false,
  adsb: false,
  acledEvents: false,
  militaryFlights: false,
  aviationIntel: false,
  diseaseIntel: false,
  forecastOverlay: false,
  theaterPolygons: false,
  convergenceRings: false,
  threatHeatmap: false,
  sigintConvergence: false,
  weatherRadar: false,
  weatherSatellite: false,
  lightning: false,
  owmTemperature: false,
  owmPrecipitation: false,
  owmClouds: false,
  owmWind: false,
  redFlagWarnings: false,
  weatherHazards: false,
  wastewaterStates: false,
  buildings3d: false,  satellites: false,
  aircraft3d: false,
  streetTiles: false,
  navigationRoute: false,
  volcanoMonitor: false,
  severeWeatherPolygons: false,
  shakemapOverlay: false,
};

const HAPPY_MOBILE_MAP_LAYERS: MapLayers = {
  gpsJamming: false,
  conflicts: false,
  bases: false,
  cables: false,
  pipelines: false,
  hotspots: false,
  ais: false,
  nuclear: false,
  irradiators: false,
  sanctions: false,
  weather: false,
  economic: false,
  waterways: false,
  outages: false,
  cyberThreats: false,
  datacenters: false,
  protests: false,
  flights: false,
  military: false,
  natural: false,
  spaceports: false,
  minerals: false,
  fires: false,
  // Data source layers
  ucdpEvents: false,
  airstrikes: false,
  strikePackages: false,
  displacement: false,
  climate: false,
  // Tech layers (disabled)
  startupHubs: false,
  cloudRegions: false,
  accelerators: false,
  techHQs: false,
  techEvents: false,
  // Finance layers (disabled)
  stockExchanges: false,
  financialCenters: false,
  centralBanks: false,
  commodityHubs: false,
  gulfInvestments: false,
  // Happy variant layers
  positiveEvents: true,
  kindness: true,
  happiness: true,
  speciesRecovery: true,
  renewableInstallations: true,
  tradeRoutes: false,
  iranAttacks: false,
  s2pimu: false,
  dayNight: false,
  faaWeatherCams: false,
  adsb: false,
  acledEvents: false,
  militaryFlights: false,
  aviationIntel: false,
  diseaseIntel: false,
  forecastOverlay: false,
  theaterPolygons: false,
  convergenceRings: false,
  threatHeatmap: false,
  sigintConvergence: false,
  weatherRadar: false,
  weatherSatellite: false,
  lightning: false,
  owmTemperature: false,
  owmPrecipitation: false,
  owmClouds: false,
  owmWind: false,
  redFlagWarnings: false,
  weatherHazards: false,
  wastewaterStates: false,
  buildings3d: false,  satellites: false,
  aircraft3d: false,
  streetTiles: false,
  navigationRoute: false,
  volcanoMonitor: false,
  severeWeatherPolygons: false,
  shakemapOverlay: false,
};

// ============================================
// VARIANT-AWARE EXPORTS
// ============================================
export const DEFAULT_PANELS = SITE_VARIANT === 'happy' ? HAPPY_PANELS : SITE_VARIANT === 'tech' ? TECH_PANELS : SITE_VARIANT === 'finance' ? FINANCE_PANELS : FULL_PANELS;
export const DEFAULT_MAP_LAYERS = SITE_VARIANT === 'happy' ? HAPPY_MAP_LAYERS : SITE_VARIANT === 'tech' ? TECH_MAP_LAYERS : SITE_VARIANT === 'finance' ? FINANCE_MAP_LAYERS : FULL_MAP_LAYERS;
export const MOBILE_DEFAULT_MAP_LAYERS = SITE_VARIANT === 'happy' ? HAPPY_MOBILE_MAP_LAYERS : SITE_VARIANT === 'tech' ? TECH_MOBILE_MAP_LAYERS : SITE_VARIANT === 'finance' ? FINANCE_MOBILE_MAP_LAYERS : FULL_MOBILE_MAP_LAYERS;

/** Maps map-layer toggle keys to their data-freshness source IDs (single source of truth). */
export const LAYER_TO_SOURCE: Partial<Record<keyof MapLayers, DataSourceId[]>> = {
  military: ['opensky', 'wingbits'],
  ais: ['ais'],
  natural: ['usgs'],
  weather: ['weather'],
  outages: ['outages'],
  cyberThreats: ['cyber_threats'],
  protests: ['acled', 'gdelt_doc'],
  ucdpEvents: ['ucdp_events'],
  displacement: ['unhcr'],
  climate: ['climate'],
  faaWeatherCams: ['faa_weather_cams'],
  adsb: ['adsb'],
  acledEvents: ['acled'],
  militaryFlights: ['adsb-military'],
  aviationIntel: ['aviation-intel'],
};

// ============================================
// PANEL CATEGORY MAP (variant-aware)
// ============================================
// Maps category keys to panel keys. Only categories with at least one
// matching panel in the active variant's DEFAULT_PANELS are shown.
// The `variants` field restricts a category to specific site variants;
// omit it to show the category for all variants.
export const PANEL_CATEGORY_MAP: Record<string, { labelKey: string; panelKeys: string[]; variants?: string[] }> = {
  // All variants — essential panels
  core: {
 labelKey: 'header.panelCatCore',
 panelKeys: ['map', 'insights', 'strategic-posture', 'live-news', 'live-webcams', 'unified-webcams', 'pinned-webcams'],
  },

  // Full (geopolitical) variant
  intelligence: {
 labelKey: 'header.panelCatIntelligence',
 panelKeys: ['threat-dashboard', 'global-risk-heatmap', 'command-center', 'competitive-hypothesis', 'competitive-hypothesis-engine', 'meta-confidence', 'meta-confidence-calibration', 'system-diagnostic', 'assumption-tracker', 'assumption-tracker-v2', 'counterfactual', 'causal-chain', 'domain-scorecard', 'behavioral-response', 'world-narrative', 'civilization-pulse', 'situation-lifecycle-tracker', 'compound-event-detector', 'mission-control-dashboard', 'alert-escalation', 'quality-debt', 'operational-playbook', 'failure-prediction', 'self-test', 'self-test-runner', 'operator-mode', 'operator-shift-report', 'intelligence-feed', 'intelligence-timeline', 'algorithm-diagnostic', 'source-confidence', 'event-store', 'belief-calibration', 'outcome-ledger', 'active-learning', 'active-learning-queue', 'improvement-scheduler', 'model-governance', 'recovery-modeling', 'bias-detection', 'contradiction-detector', 'cross-domain-contradiction-detector', 'crisis-trajectory', 'intelligence-digest', 'regional-resilience', 'algo-eval', 'backtest', 'backtest-gate', 'global-rhythm', 'temporal-anomaly-detector', 'threat-horizon', 'shadow-mode', 'shadow-comparison', 'cognitive-bias-detector', 'crisis-signature', 'predictive-crisis-index', 'collection-gap', 'safety-case', 'safety-case-dashboard', 'experiment-manager', 'domain-scorecards', 'geopolitical-event-calendar', 'signal-enrichment', 'threat-correlation-matrix', 'geospatial-clustering', 'intelligence-briefing-export', 'intelligence-index', 'situation-timeline', 'domain-dependency', 'multi-agent-review', 'repair-recommendations', 'mission-ledger-bridge', 'counterfactual-replay', 'counterfactual-reasoning', 'situation-priority-queue', 'intelligence-health-monitor', 'intelligence-loop-orchestrator', 'analyst-notebook', 'persistent-query-engine', 'evidence-graph', 'evidence-chain-builder', 'entity-registry', 'alert-trace', 'alert-rules-tuning', 'intelligence-quality-debt', 'alert-explanation', 'scenario-replay', 'playbook', 'aviation-intel', 'aviation-superpower', 'energy-superpower', 'shortage-radar', 'storm-posture', 'shortage-detail-wheat', 'shortage-detail-corn', 'shortage-detail-rice', 'shortage-detail-soybeans', 'shortage-detail-diesel', 'shortage-detail-gasoline', 'shortage-detail-natural-gas', 'shortage-detail-jet-fuel', 'maritime-intel', 'maritime-superpower', 'trade-route-risk-scorer', 'trade-disruption', 'supply-chain-disruption', 'watchlist', 'saved-places', 'saved-places-filter', 'watchlist-locations', 'watch-area-alerting', 'local-logistics', 'comms-plan', 'unified-alert-inbox', 'alert-rules', 'alert-deduplication', 'situation-awareness', 'alert-center', 'strategic-risk', 'cii', 'geo-hubs', 'intel', 'gdelt-intel', 'gdelt-monitor', 'cascade', 'telegram-intel', 'intelligence-briefing', 'ask-crystal-ball', 'survival-advisor', 'threat-synthesis', 'scenario-simulator', 'escalation-forecast', 'synthesis', 'cyber-geo', 'economic-intel', 'notification-digest', 'notification-settings', 'notification-preferences', 'notification-history', 'notification-audit', 'notification-provenance', 'trust-budget', 'intelligence-trust-budget', 'personal-relevance', 'pattern-of-life', 'course-of-action', 'kill-chain', 'orbat', 'after-action-review', 'entity-link-graph', 'timeline-scrubber', 'intel-report', 'compound-threat', 'correlation-matrix', 'correlation-map', 'mediastack-news', 'situations', 'observation-rules', 'what-changed', 'strike-package', 'strike-packages', 'api-diagnostic', 'cascade-simulator', 'feed-health', 'feed-health-dashboard', 'feed-watchdog', 'source-credibility-tracker', 'dod-news', 'nato-news', 'foreign-mil-news', 'isw-reports', 'reliefweb-crises', 'bellingcat-osint', 'acaps-crises', 'liveuamap', 'un-security-council', 'combatant-commands', 'congress-defense', 'gov-warning-convergence', 'dsca-arms-transfers', 'dod-contracts', 'wikidata-bases', 'opensanctions', 'sanctions-intel', 'infra-risk-matrix', 'earthquake-super', 'seismic-superpower', 'world-state-comparator', 'health-superpower', 'cyber-superpower', 'geopolitical-superpower', 'critical-minerals', 'alert-fatigue-dashboard', 'infrastructure-superpower', 'organized-crime-superpower', 'historical-playback', 'election-monitoring', 'nuclear-superpower', 'cyber-incident-response', 'threat-convergence', 'urban-security', 'climate-superpower', 'disaster-response', 'personal-resilience', 'geopolitical-risk', 'currency-warfare', 'signal-noise-filter', 'supply-chain-resilience', 'alliance-cohesion', 'sanctions-tracker', 'economic-coercion', 'energy-security', 'arms-proliferation', 'narcotics-trafficking', 'terrorism-superpower', 'space-militarization', 'state-fragility', 'state-capacity', 'information-operations', 'maritime-boundary', 'tech-competition', 'sms-command-interface', 'political-risk-superpower', 'global-migration-crisis', 'water-security', 'arctic-monitoring', 'climate-security-nexus', 'arctic-competition', 'urban-instability', 'cyber-espionage', 'territorial-disputes', 'great-power-competition', 'regime-stability', 'coup-risk', 'arms-sales', 'global-logistics-chokepoints', 'transnational-repression', 'corruption-index', 'electric-grid-vulnerability', 'maritime-piracy', 'conflict-escalation', 'insurgency-tracker', 'nuclear-nonproliferation', 'food-systems-geopolitics', 'drone-warfare', 'space-debris', 'border-incidents', 'disinformation-networks', 'warlord-economics', 'ai-governance', 'cyber-norms', 'digital-currency-geopolitics', 'foreign-aid-weaponization', 'debt-trap-diplomacy', 'media-freedom', 'military-exercises', 'hostage-diplomacy', 'sovereign-wealth-funds', 'tech-transfer-risk', 'global-military-spending', 'foreign-fighters', 'escalation-ladder', 'resource-nationalism', 'coercive-diplomacy', 'diplomatic-signals', 'treaty-surveillance', 'seabed-warfare', 'intl-law-violations', 'intelligence-cooperation', 'energy-weaponization', 'propaganda-tracking', 'digital-autocracy', 'foreign-investment-risk', 'gray-zone-conflict', 'nuclear-deterrence', 'travel-safety', 'global-conflict', 'strategic-deception', 'economic-espionage', 'space-weaponization', 'psychological-operations', 'mercenary-ecosystem', 'quantum-tech-race', 'semiconductor-geopolitics', 'election-interference', 'migration-crisis', 'organized-crime', 'human-rights-abuses', 'energy-geopolitics', 'sovereign-debt-crisis', 'critical-infra-attack', 'pandemic-preparedness', 'democratic-backsliding', 'financial-crimes', 'private-military', 'hybrid-warfare', 'resource-competition', 'diplomatic-crisis', 'digital-infrastructure', 'global-health-security', 'food-security-superpower', 'state-capitalism', 'coalition-dynamics', 'datacenter-readiness', 'watchboards'],  },
  regionalNews: {
 labelKey: 'header.panelCatRegionalNews',
 panelKeys: ['politics', 'us', 'europe', 'middleeast', 'africa', 'latam', 'asia'],
 variants: ['full'],
  },
  marketsFinance: {
 labelKey: 'header.panelCatMarketsFinance',
 panelKeys: ['commodities', 'markets', 'economic', 'economic-stress', 'federal-register', 'trade-policy', 'supply-chain', 'finance', 'polymarket', 'macro-signals', 'etf-flows', 'stablecoins', 'crypto', 'heatmap', 'fear-greed', 'national-debt', 'sovereign-debt', 'fuel-prices', 'fdic-failures', 'edgar-filings', 'central-bank-calendar', 'financial-superpower', 'regulatory-arbitrage', 'political-economy', 'global-logistics-chokepoints', 'warlord-economics', 'digital-currency-geopolitics', 'debt-trap-diplomacy', 'resource-nationalism', 'foreign-investment-risk', 'sovereign-debt-crisis', 'financial-crimes', 'food-systems-geopolitics', 'food-security-superpower'],
 variants: ['full'],
  },
  topical: {
 labelKey: 'header.panelCatTopical',
 panelKeys: ['energy', 'gov', 'thinktanks', 'tech', 'ai', 'layoffs'],
 variants: ['full'],
  },
  dataTracking: {
 labelKey: 'header.panelCatDataTracking',
 panelKeys: ['counterterrorism', 'extremism-tracking', 'monitors', 'cyber-threats', 'threat-inbox', 'local-ids', 'little-snitch', 'comms-health', 'power-grid', 'grid-intelligence', 'electric-grid-vulnerability', 'cve-tracker', 'vulners-cve', 'hibp-breaches', 'ipinfo-lookup', 'ucdp-events', 'nuclear-risk', 'nuclear-near-miss', 'airstrikes', 'displacement', 'security-advisories', 'bitcoin-abuse', 'reddit-osint', 'network-rules', 's2u-intel', 's2-underground-media', 'oref-sirens', 'space-weather', 'neo-tracker', 'space-security', 'space-superpower', 'spaceflight-news', 'space-launches', 'population-exposure', 'internet-disruptions', 'air-traffic', 'threat-intel-hub', 'phishstats-feed', 'urlscan-threats', 'pulsedive-intel', 'geo-intel', 'dark-web', 'anomaly-detection', 'financial-contagion', 'supply-chain-impact', 'nuclear-monitor', 'sigint-panel', 'dark-vessel', 'shadow-fleet', 'ics-ot-dashboard', 'ioc-manager', 'network-topology', 'stix-taxii', 'custom-geofence', 'sanctions-crossref', 'emergency-broadcast', 'satellite-change', 'ripe-ncc', 'ripe-atlas', 'aerospace-reentry', 'satellite-intel', 'cyber-espionage', 'political-violence', 'nuclear-deterrence', 'space-debris', 'space-weaponization', 'critical-infra-attack', 'psychological-operations', 'gray-zone-conflict', 'strategic-deception', 'economic-espionage', 'global-conflict', 'travel-safety', 'pandemic-preparedness', 'digital-infrastructure'], variants: ['full'],  },
  hazards: {
 labelKey: 'header.panelCatHazards',

 panelKeys: ['wildfire-intel', 'satellite-fires', 'firms-thermal', 'earthquakes', 'emsc-seismic', 'gdacs-alerts', 'volcano-alerts', 'volcano-monitor', 'severe-weather', 'shakealert', 'weather-hazard', 'nws-alerts', 'faa-weather-cams', 'faa-tfrs', 'tsunami-alerts', 'tropical-cyclones', 'climate', 'wildfire-incidents', 'hazmat-incidents', 'oil-spill', 'fcdo-warnings', 'dfat-warnings', 'gac-warnings', 'avalanche-hazard', 'wildfire-smoke', 'spc-mesoscale', 'amtrak-alerts', 'habsos', 'global-weather', 'extended-forecast', 'tide-predictions', 'pollen', 'weather-radar', 'goes-satellite', 'flood-monitor', 'weather-superpower'],
 variants: ['full'],
  },
  healthEnv: {
 labelKey: 'header.panelCatHealthEnv',
 panelKeys: ['hazard-alerts', 'infrastructure', 'giving', 'daily-wisdom', 'stoic-reflections', 'biblical-encouragement', 'alan-watts-reflections', 'mckenna-visions', 'disease-outbreaks', 'disease-intel', 'humanitarian-crisis', 'air-quality', 'food-insecurity', 'offline-maps', 'evacuation', 'family-tracker', 'radiation-decay', 'resource-inventory', 'water-quality', 'ecdc-surveillance', 'openaq-monitor'],
 variants: ['full'],
  },

  // Tech variant
  techAi: {
 labelKey: 'header.panelCatTechAi',
 panelKeys: ['tech-readiness', 'ai', 'tech-hubs', 'tech', 'hardware', 'cloud', 'dev', 'github', 'producthunt', 'events', 'service-status'],
 variants: ['tech'],
  },
  startupsVc: {
 labelKey: 'header.panelCatStartupsVc',
 panelKeys: ['startups', 'vcblogs', 'regionalStartups', 'unicorns', 'accelerators', 'funding', 'ipo'],
 variants: ['tech'],
  },
  securityPolicy: {
 labelKey: 'header.panelCatSecurityPolicy',
 panelKeys: ['regulation', 'policy', 'security'],
 variants: ['tech'],
  },
  techMarkets: {
 labelKey: 'header.panelCatMarkets',
 panelKeys: ['markets', 'finance', 'crypto', 'economic', 'polymarket', 'macro-signals', 'etf-flows', 'stablecoins', 'layoffs', 'monitors'],
 variants: ['tech'],
  },

  // Finance variant
  finMarkets: {
 labelKey: 'header.panelCatMarkets',
 panelKeys: ['markets', 'markets-news', 'heatmap', 'macro-signals', 'analysis', 'polymarket'],
 variants: ['finance'],
  },
  fixedIncomeFx: {
 labelKey: 'header.panelCatFixedIncomeFx',
 panelKeys: ['forex', 'bonds'],
 variants: ['finance'],
  },
  finCommodities: {
 labelKey: 'header.panelCatCommodities',
 panelKeys: ['commodities', 'commodities-news'],
 variants: ['finance'],
  },
  cryptoDigital: {
 labelKey: 'header.panelCatCryptoDigital',
 panelKeys: ['crypto', 'crypto-news', 'etf-flows', 'stablecoins', 'fintech'],
 variants: ['finance'],
  },
  centralBanksEcon: {
 labelKey: 'header.panelCatCentralBanks',
 panelKeys: ['centralbanks', 'economic', 'trade-policy', 'supply-chain', 'economic-news'],
 variants: ['finance'],
  },
  dealsInstitutional: {
 labelKey: 'header.panelCatDeals',
 panelKeys: ['ipo', 'derivatives', 'institutional', 'regulation'],
 variants: ['finance'],
  },
  gulfMena: {
 labelKey: 'header.panelCatGulfMena',
 panelKeys: ['gcc-investments', 'gccNews', 'monitors'],
 variants: ['finance'],
  },
};

// Monitor palette — fixed category colors persisted to localStorage (not theme-dependent)
export const MONITOR_COLORS = [
  '#44ff88',
  '#ff8844',
  '#4488ff',
  '#ff44ff',
  '#ffff44',
  '#ff4444',
  '#44ffff',
  '#88ff44',
  '#ff88ff',
  '#88ffff',
];

export const STORAGE_KEYS = {
  panels: 'crystalball-panels',
  monitors: 'crystalball-monitors',
  mapLayers: 'crystalball-layers',
  disabledFeeds: 'crystalball-disabled-feeds',
  deckPins: 'crystalball-deck-pins',
} as const;
