#!/usr/bin/env node
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { COMPATIBILITY } from './server-meta.mjs';
import { TOOL_INDEX, TOOL_REFERENCE, catalogSummary } from './tool-registry.mjs';

const root = dirname(fileURLToPath(import.meta.url));
const check = process.argv.includes('--check');
const registry = {
  summary: catalogSummary(),
  compatibility: COMPATIBILITY,
  categories: TOOL_INDEX.categories,
  topics: TOOL_INDEX.topics,
  examples: TOOL_INDEX.examples,
  tools: TOOL_REFERENCE,
};
const generated = new Map([
  [join(root, 'docs', '_index.json'), `${JSON.stringify(TOOL_INDEX, null, 2)}\n`],
  [join(root, 'docs', 'registry.json'), `${JSON.stringify(registry, null, 2)}\n`],
  [join(root, 'docs', 'registry.md'), renderRegistryMarkdown(registry)],
]);

if (check) {
  let stale = false;
  for (const [target, content] of generated) {
    const current = await readFile(target, 'utf8').catch(() => '');
    if (current !== content) {
      console.error(`${target} is stale. Run npm run docs:generate.`);
      stale = true;
    }
  }
  if (stale) {
    process.exitCode = 1;
  }
} else {
  for (const [target, content] of generated) {
    await writeFile(target, content);
    console.log(`Generated ${target}`);
  }
}

function renderRegistryMarkdown(reference) {
  const rows = Object.entries(reference.tools).map(([name, tool]) => (
    `| \`${name}\` | ${tool.category} | ${tool.permission.label} | \`${tool.permission.code}\` | ${tool.description} |`
  ));
  return `# Crystal Ball Agent Tool Registry

Generated from \`tool-registry.mjs\`. Do not edit this file by hand.

${reference.summary}. MCP protocol ${reference.compatibility.protocol}; server ${reference.compatibility.server.current}; skill contract ${reference.compatibility.skillContract.current}.

| Tool | Category | Permission | Code | Purpose |
| --- | --- | --- | --- | --- |
${rows.join('\n')}
`;
}
