/**
 * Competitive Hypothesis Engine Panel — surfaces every active
 * HypothesisSet generated by the engine. Each set expands to show
 * its 3 hypotheses with type badge, confidence bar, claim text, and
 * evidence count. Consensus banner shown when the leader pulls
 * clearly ahead.
 *
 * Vanilla TS panel — subscribes to the engine for push-driven
 * refresh and falls back to a 10s timer.
 */

import { Panel } from './Panel';
import { escapeHtml } from '@/utils/sanitize';
import {
  getCompetitiveHypothesisEngine,
  type Hypothesis,
  type HypothesisSet,
  type HypothesisStatus,
  type HypothesisType,
} from '@/services/intelligence/competitive-hypothesis';

const REFRESH_MS = 10_000;

const TYPE_LABEL: Record<HypothesisType, string> = {
  primary: 'Primary',
  alternative: 'Alternative',
  'devil-advocate': 'Devil’s Advocate',
};

const TYPE_COLOR: Record<HypothesisType, string> = {
  primary: '#4a9eff',
  alternative: '#a78bfa',
  'devil-advocate': '#fb923c',
};

const STATUS_COLOR: Record<HypothesisStatus, string> = {
  active: 'var(--text-secondary,#aaa)',
  supported: 'var(--severity-info,#22c55e)',
  refuted: 'var(--severity-high,#f87171)',
  merged: '#a78bfa',
};

export class CompetitiveHypothesisEnginePanel extends Panel {
  private refreshTimer: ReturnType<typeof setInterval> | null = null;
  private unsubscribe: (() => void) | null = null;
  private expandedSituationIds = new Set<string>();

  constructor() {
    super({
      id: 'competitive-hypothesis-engine',
      title: 'Competing Hypotheses (Engine)',
      showCount: true,
      trackActivity: true,
      infoTooltip:
        'For each active Situation, generates a primary explanation plus an alternative and a devil’s-advocate framing. Evidence additions re-normalize confidences across the set; a consensus banner appears when the leader pulls clearly ahead.',
    });
    this.render();
    this.refreshTimer = setInterval(() => this.renderWhenVisible(() => this.render()), REFRESH_MS);
    this.unsubscribe = getCompetitiveHypothesisEngine().subscribe(() => this.render());
    this.attachHandlers();
  }

  public override destroy(): void {
    if (this.refreshTimer !== null) {
      clearInterval(this.refreshTimer);
      this.refreshTimer = null;
    }
    this.unsubscribe?.();
    this.unsubscribe = null;
    super.destroy();
  }

  // ── Rendering ──────────────────────────────────────────────────────

  private render(): void {
    try {
      const sets = getCompetitiveHypothesisEngine().getAllSets();
      this.setCount(sets.length);
      this.setContent(sets.length === 0 ? this.renderEmpty() : this.renderSets(sets));
    } catch (error) {
      this.setContent(
        `<div style="padding:12px;color:var(--severity-critical,#dc2626);font-size:12px;">Competing-hypothesis render error: ${escapeHtml(String(error))}</div>`,
      );
    }
  }

  private renderEmpty(): string {
    return `<div style="padding:16px;display:flex;flex-direction:column;gap:8px;font-size:12px;color:var(--text-secondary,#aaa);">
      <div style="font-size:13px;font-weight:600;color:var(--text-primary,#fff);">No hypothesis sets generated</div>
      <div>Call <code>getCompetitiveHypothesisEngine().generate(situationId, domain, severity)</code> for an active Situation to populate this panel.</div>
    </div>`;
  }

  private renderSets(sets: readonly HypothesisSet[]): string {
    return `<div style="padding:12px;display:flex;flex-direction:column;gap:10px;font-size:12px;">
      ${sets.map((s) => this.renderSet(s)).join('')}
    </div>`;
  }

  private renderSet(set: HypothesisSet): string {
    const expanded = this.expandedSituationIds.has(set.situationId);
    const consensusBanner = set.consensusReached
      ? `<div style="font-size:10px;padding:2px 7px;border-radius:3px;background:rgba(34,197,94,0.15);color:#22c55e;font-weight:700;text-transform:uppercase;letter-spacing:0.04em;">Consensus</div>`
      : '';
    const leaderClaim = set.leadingHypothesis?.claim ?? '—';
    const leaderConfidence = set.leadingHypothesis
      ? `${Math.round(set.leadingHypothesis.confidence * 100)}%`
      : '—';
    return `<div class="ch-set" data-situation-id="${escapeHtml(set.situationId)}" style="border:1px solid var(--border-subtle,#333);border-radius:4px;background:rgba(255,255,255,0.02);">
      <div class="ch-set-header" style="padding:10px 12px;display:flex;gap:10px;align-items:center;flex-wrap:wrap;cursor:pointer;">
        <strong style="font-size:13px;">${escapeHtml(set.situationId)}</strong>
        <span style="font-size:11px;color:var(--text-secondary,#aaa);flex:1;min-width:160px;">leader: ${escapeHtml(leaderClaim)}</span>
        <span style="font-size:11px;font-weight:700;color:var(--text-primary,#fff);">${escapeHtml(leaderConfidence)}</span>
        ${consensusBanner}
        <span style="font-size:10px;color:var(--text-secondary,#aaa);">${expanded ? '▼' : '▶'}</span>
      </div>
      ${expanded ? this.renderHypotheses(set) : ''}
    </div>`;
  }

  private renderHypotheses(set: HypothesisSet): string {
    return `<div style="padding:0 12px 12px;display:flex;flex-direction:column;gap:6px;">
      ${set.hypotheses.map((h) => this.renderHypothesis(h, set.leadingHypothesis?.id === h.id)).join('')}
    </div>`;
  }

  private renderHypothesis(h: Hypothesis, isLeader: boolean): string {
    const typeColor = TYPE_COLOR[h.type];
    const statusColor = STATUS_COLOR[h.status];
    const pct = Math.round(h.confidence * 100);
    const leaderRing = isLeader ? `border:1px solid ${typeColor};` : 'border:1px solid var(--border-subtle,#333);';
    return `<div style="padding:8px 10px;${leaderRing}border-radius:4px;background:rgba(255,255,255,0.02);">
      <div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap;">
        <span style="font-size:10px;padding:1px 6px;border-radius:3px;background:${typeColor}22;color:${typeColor};font-weight:700;text-transform:uppercase;letter-spacing:0.04em;">${escapeHtml(TYPE_LABEL[h.type])}</span>
        <strong style="font-size:12px;flex:1;min-width:160px;">${escapeHtml(h.claim)}</strong>
        <span style="font-size:10px;color:${statusColor};text-transform:uppercase;letter-spacing:0.04em;font-weight:700;">${escapeHtml(h.status)}</span>
        <span style="font-size:11px;font-weight:700;color:var(--text-primary,#fff);width:36px;text-align:right;">${pct}%</span>
      </div>
      <div style="margin-top:5px;display:flex;gap:8px;align-items:center;">
        <div style="flex:1;height:6px;background:rgba(255,255,255,0.04);border-radius:2px;overflow:hidden;">
          <div style="width:${pct}%;height:100%;background:${typeColor};"></div>
        </div>
        <span style="font-size:10px;color:var(--text-secondary,#aaa);">${h.evidence.length} evidence</span>
      </div>
      <div style="font-size:11px;color:var(--text-secondary,#aaa);margin-top:5px;">${escapeHtml(h.rationale)}</div>
    </div>`;
  }

  // ── Events ────────────────────────────────────────────────────────

  private attachHandlers(): void {
    this.content.addEventListener('click', (e) => this.onClick(e));
  }

  private onClick(event: MouseEvent): void {
    const target = event.target as HTMLElement | null;
    if (!target) return;
    const header = target.closest<HTMLElement>('.ch-set-header');
    if (!header) return;
    const setEl = header.parentElement as HTMLElement | null;
    const situationId = setEl?.dataset.situationId;
    if (!situationId) return;
    if (this.expandedSituationIds.has(situationId)) {
      this.expandedSituationIds.delete(situationId);
    } else {
      this.expandedSituationIds.add(situationId);
    }
    this.render();
  }
}
